### ISSUE TITLE
Authentication should hide token inputs when TRY is disabled

### ISSUE THREAD

**Issue by ArchMotif** [rapi-doc/RapiDoc#1005]
If I'm running with TRY disabled, it's misleading/confusing to see inputs for an API token or other auth fields.  There's also a red label above telling me I need to enter an API token.

![Screenshot 2024-04-02 at 12 17 59 PM](https://github.com/rapi-doc/RapiDoc/assets/5600894/bca50078-d5ba-4cb2-82e1-d30498176319)

**Comment by mrin9** [comment]
fixed by bb8ec2d40293c6f683e89b80a53a7b545b32c24f
