### ISSUE TITLE
Unable to grab js file from unpkg

### ISSUE THREAD

**Issue by bjornharvold** [rapi-doc/RapiDoc#1006]
<img width="1800" alt="Screenshot 2024-04-12 at 15 52 33" src="https://github.com/rapi-doc/RapiDoc/assets/641791/a6e556a8-92e1-417b-9664-0a9e56a99ca3">

**Comment by BogdanAlexandru09** [comment]
Got the same output hours ago.

What was curious was that the examples from the web page worked, and I just changed the script tag source with this: https://rapidocweb.com/rapidoc-min.js.

Seems now it is back up though.

**Comment by bjornharvold** [comment]
Yes works again. Is this an unpkg issue or a rapidoc issue? Other JS files (jquery, react ++) from unpkg worked fine during downtime.
