### ISSUE TITLE
[Feature Request] Use Monaco editor for Request Body

### ISSUE THREAD

**Issue by douglasg14b** [rapi-doc/RapiDoc#1010]
The `textarea` could utilize the [Monaco](https://github.com/microsoft/monaco-editor) editor to provide syntax highlighting and "normal" text editor features for request JSON (or other languages).

Editor preview: https://microsoft.github.io/monaco-editor/

This would be a much improved user experience when writing requests both for syntax highlighting, code formatting, syntax errors, intellisense, and other "sugar" features that make the request body more pleasant to write.

![image](https://github.com/rapi-doc/RapiDoc/assets/1400380/ae5b8b22-8530-4637-abb6-55e7560c52ea)

vs 

![image](https://github.com/rapi-doc/RapiDoc/assets/1400380/81d23cd4-a16a-44b1-8037-2159ec98ba0c)

**Comment by emericcolombe** [comment]
Awesome idea !

**Comment by mrin9** [comment]
one of the goal of this web-component is to be extremely lightweight in size. So that the entire thing can be bundled into a single file . Therefore we are very careful in choosing dependencies or even upgrading them Monaco dont bring us a lot of advantage compared to its size penalty.

**Comment by douglasg14b** [comment]
@mrin9 I think this is value to keep open, there is a big gap here that remains unfilled. Such QoL could also be bundle/option dependent if the _only_ option is monaco.

That said:

Monaco can be bundled into a single file (19.9KB), which to be fair, is larger than `prism` or `marked` (6.9KB & 10.7KB) which you already bundle. But not exactly by an egregious amount.

And if not monaco, then there are other ways to perform syntax highlighting on JSON that would be useful here.

**Comment by douglasg14b** [comment]
This seems like something I could stab at next time I have a schedule gap, don't hold your breath though, on crunch-time right now 😅
