### ISSUE TITLE
Error on CSS-parts "Labels" documentation

### ISSUE THREAD

**Issue by aaSchcolnik** [rapi-doc/RapiDoc#1012]
# Page with the error:
https://rapidocweb.com/css-parts.html

# Error:
The current css name you're giving out for operation method is incorrect, it should be `label-operation-method`.

## Part with the error:
![CleanShot 2024-06-03 at 7 21 54@2x](https://github.com/rapi-doc/RapiDoc/assets/86570811/79ff8eba-c338-4a87-a2a3-59fb6ac6e59b)

## Fix
**Instead of:** `label-operations-method`
**It should be:** `label-operation-method`

**Comment by mrin9** [comment]
thanks for bringing into our attention
