### ISSUE TITLE
Is the Rapidoc project being maintained actively or any replacement?

### ISSUE THREAD

**Issue by sberwal** [rapi-doc/RapiDoc#1020]
Hi,

It seems there have been no new release since Jan 2023 and many issues are lying unanswered.

This raises a very pertinent question. 

Is rapidoc going to be actively maintained anymore?

Has anyone tried any other alternates to Rapidoc with similar kind of ease to create the API Documentation on top of their swaggers which is actively maintained?

Thanks,
Suraj Berwal

**Comment by wparad** [comment]
@sberwal we've been maintaining a fork for years over at [OpenAPI Explorer](https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#openapi-explorer)

**Comment by mrin9** [comment]
yes it is
