### ISSUE TITLE
API Endpoint operation headers disappeared in latest version

### ISSUE THREAD

**Issue by neptunecentury** [rapi-doc/RapiDoc#1025]
Hi, we have been using the CDN with version 9.3.4 for some time, and the side navigation operation headers were showing before. After this recent update in 9.3.5, the navigation tags are missing.
![image](https://github.com/user-attachments/assets/0d30ac4d-ec33-40bd-b28c-e27dbfbba003)

I have manually downloaded 9.3.4 and removed CDN for now until the issue is resolved. Is there anything on my end I need to update to get this working again?

Thanks

**Comment by mrin9** [comment]
can you provide me with a small sample spec where i can reproduce this ?

**Comment by douglasg14b** [comment]
We're also seeing the same thing on all of our Rapidoc sites

**Comment by neptunecentury** [comment]
Actually, the demo page for Azure AD is broken too.
You can see it here:
https://rapidocweb.com/examples/api-demo.html
Select AzureAD from options on the right and you will see the headers missing

**Comment by mrin9** [comment]
it is showing fine on my system Macbook (on chrome and safari)
<img width="1478" alt="image" src="https://github.com/user-attachments/assets/8ace12e8-4b7a-4860-947d-1c03bbc4a75a">

**Comment by neptunecentury** [comment]
> it is showing fine on my system Macbook (on chrome and safari) <img alt="image" width="1478" src="https://private-user-images.githubusercontent.com/5056899/368724896-8ace12e8-4b7a-4860-947d-1c03bbc4a75a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2OTA5ODEsIm5iZiI6MTcyNjY5MDY4MSwicGF0aCI6Ii81MDU2ODk5LzM2ODcyNDg5Ni04YWNlMTJlOC00YjdhLTQ4NjAtOTQ3ZC0xYzAzYmJjNGE3NWEucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDkxOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA5MThUMjAxODAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODAxZTc3ZTIyZDFkY2FhYmQ2NjVmYmZiODNhOTIyYzQzNzU2MjMxNzMxZmVjNGZhOWYxMWFmYWUyNzA1MGQxNyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.wR7XKxESSlY6Cc8WcJH0_bVFhPs-MqjJOSgQvBRySGs">

![image](https://github.com/user-attachments/assets/5164fa36-024f-4e11-b885-611ad95bcc36)

The header in your screenshot is missing. Circled red

**Comment by neptunecentury** [comment]
The gitlab example is working
![image](https://github.com/user-attachments/assets/01ab6bbd-b040-427e-be6f-3cddab261be6)

**Comment by mrin9** [comment]
okay got it, lemme check

**Comment by mrin9** [comment]
@neptunecentury is your sepc `swagger: "2.0"` ?

**Comment by neptunecentury** [comment]
Well, we generate swagger 2.0, but use an API to convert it to OpenAPI v3 using the swagger converter here https://converter.swagger.io/api/convert

**Comment by douglasg14b** [comment]
We generate `3.0` directly, if that's relevant.

**Comment by mrin9** [comment]
Is now fixed in release `9.3.6` 

It was introduced due to a new vendor-extention `x-displayName` that was added which now allows you to provide more descriptive definitions for the tags. 
Refer to https://github.com/rapi-doc/RapiDoc/blob/master/docs/specs/tag-displayname.yaml  for its usage

Thanks for pointing out the issue !!!
