### ISSUE TITLE
Server selection displays secondary, unsynchronised dropdown

### ISSUE THREAD

**Issue by ShadowLNC** [rapi-doc/RapiDoc#1026]
We've been using RapiDoc for a while now, and we're quite happy with it (thanks for maintaining it!) - this appears to be a recent change, we only noticed this yesterday, but it might have been there for a few weeks, I am not sure.

Testing with https://rapidocweb.com/examples/example1.html

If I use this [OpenAPI 3.1.0 schema with multiple servers](https://cdn.jsdelivr.net/npm/@scalar/galaxy/dist/latest.yaml) (admittedly not the local schema I was testing with, which is an internal API, but it shows the same issue), then each endpoint has its own dropdown for the server selection, which is not linked to the main server section at the top.

There appears to be 3 problems with this new dropdown:

1. It's not synced (to the main section, or even other dropdowns), so you can have a different server selected for each endpoint - this is confusing and causes requests to go to unintended servers
2. It lists each server twice
3. It doesn't seem to work with parameterised server URLs like `{protocol}://localhost`

It seems like it might only show up in OpenAPI 3.1.0 specs? Is there a way to disable this new dropdown? I couldn't find anything in the docs about it.

**Comment by mrin9** [comment]
can you provide me with a sample doc for me to produce the issue ?
for server variable use this as the [example](https://rapidocweb.com/examples/server-vars.html)

**Comment by ShadowLNC** [comment]
In your linked example, the OpenAPI version is 3.0.2. If I change it to 3.1.0 as mentioned, the issue occurs without any other changes (using the same HTML as well).

As you can see in my screenshot, I have selected a (non-default) server, but this new dropdown still shows the old server. Since I want to be able to select/change my API server, I don't think the `default-api-server` can help here?

<img width="860" alt="image" src="https://github.com/user-attachments/assets/b18d732f-74de-411c-aa1b-3da06dc9cc61">
