### ISSUE TITLE
[Issue] before-render event payload changed after update to 9.3.6

### ISSUE THREAD

**Issue by bandantonio** [rapi-doc/RapiDoc#1030]
If anyone has encountered the same issue as me when working with custom events (specifically, `before-render`), be aware that its payload has changed in 9.3.6:

9.3.4:

```js
rapidocElement.addEventListener('before-render', (event) => {
  if (event.target.__specUrl) {
      // rest of the code
  }
});
```

9.3.6:
In the code above, the `event.target.__specUrl` returns `undefined`. To workaround it: 

```js
rapidocElement.addEventListener('before-render', (event) => {
  if (event.target.attributes['spec-url'].value) {
      // rest of the code
  }
});
```

**Comment by mrin9** [comment]
although this is an internal representation of various html elements inside `<rapi-doc>` web component, but I can imagine how in certain cases it may be needed.

Thanks for sharing it
