### ISSUE TITLE
improve tree shakability - reduce size 

### ISSUE THREAD

**Issue by christophe-g** [rapi-doc/RapiDoc#1032]
First of all - thanks million for this. It is great, and I love it is using lit ! 

It would be great if we could make better use of ESM and avoid potential code dupe when consuming Rapidoc. 

For instance, I would like to avoid re-importing `lit`, `marked` or `Prism` (contained in the dist file) if I consume it in a project that already import those dependencies.

**Comment by christophe-g** [comment]
Related discussion: https://github.com/shoelace-style/shoelace/issues/559

**Comment by mrin9** [comment]
please refer my comments in the PR #1033 and the reason for closing it. You may create a new issue as a feature-request to generate `ESM` build if you like to track it and may contribute towards it when we start that branch
