### ISSUE TITLE
Object or null VS. String | null

### ISSUE THREAD

**Issue by neptunecentury** [rapi-doc/RapiDoc#1048]
I noticed something interesting in the schema table, where it mentions the data type and whether or not it can accept null. It seems that for most types, it is shown as
```
string | null
```
note the pipe character.
But for objects, its listed as:
```
object or null
```
Note the use of or instead of |. Is there a meaning behind the difference? Is there a way to make it all the same, (like make them all use | (pipe))?
Image for reference.
![image](https://github.com/user-attachments/assets/38cc65b6-e499-49f2-89a4-50f0aadfee8f)

Thanks for any insights!

**Comment by mrin9** [comment]
how are you providing ur dataType based on the OpenAPI version there are two ways to provide how the `nulls` are defined 

OpenAPI 2.0
- Do not support `null`

OpenAPI - 3.0 
```yml
type: string
nullable: true
```

OpenAPI - 3.1
```yml
type: ['null', string]
```
or 

```yml
oneOf:
  - type: 'null' 
  - type: string
```
In addition to that there are languages such as JavaScript where `null` is an `object` too 
so depending on various combinations the renderer may be talking multiple code paths and that might have resulted into how it is being rendered. 
but there is no semantic difference between `object or null` and ` string | null`

**Comment by neptunecentury** [comment]
Our spec is 3.0 and our Schema has a property that looks something like this:
```
"MyObjectPropertyName": {
                        "description": "Some desc...",
                        "nullable": true,
                        "allOf": [
                            {
                                "$ref": "#/components/schemas/SomeOtherObjectType"
                            }
                        ]
                    }
```

The explorer will show the type as "object or null"
Just curious why it is that way vs
```
"MyStringPropertyName": {
                        "type": "string",
                        "description": "Some desc about the property",
                        "nullable": true
                    }
```
This property will be displayed as "string | null"

Thanks again
