### ISSUE TITLE
Try feature for an API with empty response but success status code shows error

### ISSUE THREAD

**Issue by sanjogs** [rapi-doc/RapiDoc#1049]
It seems like there is an issue with the TRY feature of Rapidoc viewer. When trying an API that returns success code without any response body, following error is shown. I was expecting this to show the status code. I think it's Okay for some REST API's to not have a response body like DELETE methods, please advise.

**Response Status: Cannot read properties of null (reading 'split') (CORS or Network Issue)**

![image](https://github.com/user-attachments/assets/798858a8-3739-404e-b9f9-a19d37eaea3e)

**Comment by mrin9** [comment]
Which version of RapiDoc are you using ?
can you provide me a sample spec ? 
- specially how are you defining the `content-type`  of responses with no response body in your spec
- also share the actual response headers you are receiving from the server including `content-disposition` if any
- did you made sure that `content-disposition` response headers you are receiving from the server is accessible by the client using `Access-Control-Expose-Headers`

**Comment by sanjogs** [comment]
The content type and content disposition is not explicitly being set but the content-length is set to 0. Please check the response headers below:

![image](https://github.com/user-attachments/assets/91bc3ede-ffe2-4d1a-91e4-a62ca2ccc694)

Also i've attached the sample spec. I extracted out only related path
[extracted_spec.json](https://github.com/user-attachments/files/17464254/extracted_spec.json)

**Comment by sanjogs** [comment]
The version we are using is 9.3.6

**Comment by mrin9** [comment]
can you try with `v93.8` there was a fix in this version #1039 it might be related

**Comment by sanjogs** [comment]
Thanks @mrin9. It actually works with latest version.
