### ISSUE TITLE
XML : missing namespace + incorrect name for array items 

### ISSUE THREAD

**Issue by bligny** [rapi-doc/RapiDoc#173]
Given the following (Swagger v2) specs:

```yaml
responses:

   HeadpointPortfolio:        
    schema:
      type: array     
      xml:
        name: headpoints
        namespace: 'http://erpgis.haulogy.net/api/v1/crm'
        wrapped: true
      items:
        $ref: '#/definitions/HpPortfolioEntry'


definitions:

   HpPortfolioEntry:    
    type: object
    xml:
      namespace: 'http://erpgis.haulogy.net/api/v1/crm'
      name: headpoint          
```

The proposed xml response is:
![image](https://user-images.githubusercontent.com/19853549/78380234-d593bd80-75d3-11ea-996f-d863233ae4d5.png)

having two issues:
- xml namespaces is not rendered (red arrow)
- entries of array do not use the provided xml element name  (green arrow)

Here is the output of SwaggerUI:
![image](https://user-images.githubusercontent.com/19853549/78380115-a8470f80-75d3-11ea-881c-851d0c82a2be.png)

**Comment by mrin9** [comment]
Thanks for the detailed use case and screenshot !!!
Our schema to XML converter is pretty rudimentary, 
we just started providing this feature from `7.5.0`, will be improving it soon

**Comment by mohannad-musleh** [comment]
@mrin9 any updates regarding this issue?

**Comment by Layap** [comment]
@mrin9 has this been fixed or something that is being worked upon? Thanks!

**Comment by lothargrieb** [comment]
I changed from swagger to rapidoc. I'am very satisfied with seemless integration into our backend.
But is there any progress with xml rendering?
or an entry point to do something myself?

**Comment by mrin9** [comment]
for test case checkout - https://rapidocweb.com/examples/xml.html

for using and testing on your end pick `rapidoc-min.js` from `dist`  folder in this repo
