### ISSUE TITLE
Feature Request- Support for Links and ExternalDocs

### ISSUE THREAD

**Issue by LevinGuy** [rapi-doc/RapiDoc#226]
Hi,

RapiDoc does not support Links at the moment, for example:
https://github.com/OAI/OpenAPI-Specification/blob/master/examples/v3.0/link-example.yaml

Thanks,
Guy

**Comment by mrin9** [comment]
yep neither `Links` nor `External-Docs` are supported as yet. We have it in our roadmap but cannot commit to any timeline as we need to collect considerable user-feedbacks and few design alternatives from our design team.

I will leave this open for people to add any suggestions/feedback on these two features

**Comment by ralpha** [comment]
Would be a fan to see external docs implemented! Don't have suggestions on how to show this right now.

**Comment by mrin9** [comment]
just an FYI, you always have the option to use markdown and create internal and external links in your document

**Comment by elipinska** [comment]
I'd like to see this implemented too, it would be handy to be able to link to external documentation from the top-level tags, e.g. turning this into a menu item in the sidebar:

```
tags:
  - name: Additional docs
    externalDocs:
      url: '/url/to/additional/docs'
```

**Comment by wellsb1** [comment]
+1 for links and externalDocs.  New user of RapiDoc and already a huge fan!

**Comment by mrin9** [comment]
RapiDoc offers many ways to create and customize internal and external links. checkout #414 and example https://mrin9.github.io/RapiDoc/examples/links.html on creating links

**Comment by mrin9** [comment]
fixed by https://github.com/rapi-doc/RapiDoc/commit/e137d2112b638089e53979cb0fd071a83e36de7d
