### ISSUE TITLE
sponsorship?

### ISSUE THREAD

**Issue by ahmadnassri** [rapi-doc/RapiDoc#429]
as a thankful user of RapiDoc, I'm wondering if you are accepting any sponsorship or donations ... :)

**Comment by mrin9** [comment]
We will gladly accept any sponsorship or donation if you feel that our work have helped your cause. Most of us in the team work on RapiDoc in their free/personal time and any kind of appreciation will encourage us in our work.

We do not have any funding channel, so for now http://paypal.me/mrin is where we can accept 

Thankyou for your offer and support, It really means a lot

**Comment by mrin9** [comment]
Just wanted to give a shout out to @tjperry07. 
We received your generous donation and everyone in the team is very much upbeat about it.
yay !!!

**Comment by ahmadnassri** [comment]
may I suggest setting up a GitHub Sponsors link as well?

**Comment by mrin9** [comment]
first of all a big thanks from all of our team  @ahmadnassri  for your generous donation 

> may I suggest setting up a GitHub Sponsors link as well?

I will bring this up in the discussion,

our only regular sponsor from mid of last year have transitioned to an adhoc/informal sponsor. So, until now we have'nt given much of a thought to it also the fact that most of us work on it for the love of it.

But, we do have to think about a sustenance model and we felt a huge boost knowing that people outside of our sponsor are willing to bet on the product.

**Comment by mrin9** [comment]
closing this as zuplo is our new sponsor !!!
