### ISSUE TITLE
Feature Request- Support for storage request parameters in localStorage

### ISSUE THREAD

**Issue by xunki** [rapi-doc/RapiDoc#471]
Hi,
I want record request parameters when i click `Try` button, and load it in the page load, then i can use the parameters next time.

I Try:
  I use `before-try` event record the parameters in localStorage, But i can't load the parameters in page load.

**Comment by xunki** [comment]
`read`

**Comment by mrin9** [comment]
fixed by https://github.com/mrin9/RapiDoc/pull/614

**Comment by mrin9** [comment]
fixed by https://github.com/rapi-doc/RapiDoc/pull/614
