### ISSUE TITLE
Components are lost in Request/Response

### ISSUE THREAD

**Issue by adaliszk** [rapi-doc/RapiDoc#478]
While components can be enabled and can be viewed in focused render style, the Request, and Response schema does not reference them either way of the show-components enabled or disabled.

### Current behavior

RapiDoc does use the components, the title, and descriptions for example fetched correctly, but there is no link to the object itself. The only time you can see them when you use `oneOf` or `anyOf`, but even then they are not linked to the components themselves, and you have to name them instead of using the key in the components.

<img width="800" alt="oneOf-example" src="https://user-images.githubusercontent.com/5189131/119323852-6e294900-bc7f-11eb-94df-f4b3ab3f5788.png">

### Expected behavior

Whenever a `$ref` is used, the given property would be highlighted with the key of the reference just like how `onOf` and `anyOf` works but without those headers. Furthermore, they should be linked to the given component's hash URL so people can easily click on it and view a more detailed section about it.

### Repro

Use https://petstore.swagger.io/v2/swagger.json and see how none of the `$ref`'s are actually referenced in any of the Request or Response schemas.

**Comment by mrin9** [comment]
> While components can be enabled and can be viewed in focused render style, the Request, and Response schema does not reference them either way of the show-components enabled or disabled.

Some of the design decisions are made based user feedbacks we received. As we cater to various types of users (tech-writers, api-users, api-developers etc). 

The situation you explained may be a good thing to have for an API developer or an API document composer who would be interested in knowing how the schema is composed and what are the common-reusable parts but is not super useful to an api-user or a tech-writer who is just interested in the final schema, for them this would be a noise/distraction or may lead to confusion.

We can introduce a switch to show/hide links on schema, for this we need to evaluate the performance impact on larger spec.
schema rendering is complex and has a potential to impact performance.

I will mark this as a feature request for now, but open to PRs where an option can be provided to show links to schema components.

**Comment by adaliszk** [comment]
> The process will take time as the next feedback round is 2-3 months away, but meanwhile open to PRs where an option can be provided to show links to schema components.

Thank you, I might do open a PR, doesn't look too difficult to add as technically everything is there, though I'm a bit afraid to change anything as there is no test coverage.


> The situation you explained may be a good thing to have for an API developer or an API document composer who would be interested in knowing how the schema is composed and what are the common-reusable parts ...

It's a bit more than just readability to have the references/types instead of a merged JSON. What seemed to be the case for 4 companies I've seen in the past 5 years is that when you do use Swagger/Open-APIs heavily you rarely actually write the request yourself. What usually happens is that you generate an API client, and in that you actually work with the types using the operations itself.

Now for that API client case it actually does not matter if you even render the Request/Response on a docs page, what matters there is to know which Models (Schemas) are used because not all IDEs do good autocompletion. However, when you do need to debug the Request/Response, it was extremely useful to have those Models highlighted in the JSON tree. Found many implementation vs documentation mistakes were that way really easily, and knew which Model to change instantly.

> ... not super useful to an api-user or a tech-writer who is just interested in the final schema, for them this would be a noise/distraction or may lead to confusion.
>
> We can introduce a switch to show/hide links on schema, for this we need to evaluate the performance impact on larger spec.
schema rendering is complex and has a potential to impact performance.

My experience with that is that those who only interested in the final schema, they actually look the example provided and not the schema itself. Though the option to render either way is a really good idea, especially if you can set that globally to what should be the default or if swapping is even allowed.

As for performance, if you only render one Request/Response block at a time, then it should be relatively fine. What's not on the screen that does not matter, you can set up an Intersection Observer to quickly re-render things that are just about to get into the viewport. That's the usual way to handle very long documents anyway 😉 

> I will mark this as a feature request for now, and add this proposal to our internal users feedback as it needs to be backed up by some data

What kind of data do you looking for?

There is a generic Open-API client that is often used:
- https://github.com/swagger-api/swagger-js

The Client generation happens with these (or many custom ones):
- https://github.com/swagger-api/swagger-codegen
- https://github.com/OpenAPITools/openapi-generator

There are plenty of talks from many big companies about this code-generation topic.

**Comment by mrin9** [comment]
> I might do open a PR, doesn't look too difficult to add as technically everything is there, though I'm a bit afraid to change anything as there is no test coverage.

We took an initial dig. An overly composed schema adds too many links. It also mandates to open up the component section where the schema links take it do.

Not having test coverage is an hindrance to us too for making overly complicated changes. 
It needs a lot of effort to create a DOM based test automation for various different scenarios and maintaining it over time when features are added or removed. 

As of now we rely mostly on manual testing with some predefined specs that covers most of the scenarios.

However, I can take a look at a PR if you plan to contribute. The way I will approach is to do it in several PRs and we can give you a feedback what's working and what's not

For now will close this issue. Please open a new one when you are ready with an initial PR
