### ISSUE TITLE
Feature Request - add possibility to show/hide examples

### ISSUE THREAD

**Issue by phoenixxn** [rapi-doc/RapiDoc#494]
In big projects where migration to OpenAPI cannot be done in one go examples can look ugly when no real values provided, making sandbox useless (sending sandbox request wit auto-generated values is worthless).

Thus it's worth adding show-examples option, that will allow to hide/show examples for such projects.

**Comment by mrin9** [comment]
please re-submit the PR as it did not expected the way it should work. could be due to accidental overwrite during resolving merge conflicts
