### ISSUE TITLE
nav-hover-text-color is used for selected section

### ISSUE THREAD

**Issue by afranke** [rapi-doc/RapiDoc#559]
In modes with the sidebar, there is no dedicated `nav-selected-text-color` and `nav-hover-text-color` is used for that instead. That may result in unreadable text because of contrast, with no way to fix it.

Example color combination that is problematic:
```
theme="light"
nav-bg-color="#ffffff"
nav-text-color="#000000"
nav-hover-bg-color="#000000"
nav-hover-text-color="#ffffff"
primary-color="#000000"
```

**Comment by mrin9** [comment]
sure, we will take a look at that. but for now did you tried to style the nav-bar with 
```html
<style>
    rapi-doc::part(section-navbar) { /* <<< targets navigation bar */
      background: linear-gradient(90deg, #3d4e70, #2e3746);
     <!-- provide other style overrides --> 
    }
</style>
```
read all about advance styling here https://mrin9.github.io/RapiDoc/css-parts.html

**Comment by afranke** [comment]
I did try this, but I didn’t manage to specifically change the background color of selected menu items this way. I guess part of the problem stems from `src/style/nav-styles.js` line 138 where `color:var(--nav-hover-text-color);` is used but the matching `background-color:var(--nav-hover-bg-color)` is not. Adding that would already address the contrast issue, until a `nav-active-{bg,text}-color` pair is available.

**Comment by afranke** [comment]
Pull request incoming, with a proper fix. :smile:
