### ISSUE TITLE
focus mode example carried to another API

### ISSUE THREAD

**Issue by neildchen** [rapi-doc/RapiDoc#726]
First I want to thank you for such a great piece of work! 
I tried searching around and could not find similar feedback,  so here comes my question:

![Desktop_007](https://user-images.githubusercontent.com/8392135/164134266-6d686a98-1443-4bf9-8f25-158fa3ba9dd2.png)

![Desktop_008](https://user-images.githubusercontent.com/8392135/164134285-ae26b405-a379-4078-a685-952e8d20003f.png)

![Desktop_009](https://user-images.githubusercontent.com/8392135/164134392-083b1598-6593-4d18-b07f-996fcce49f0b.png)

In fact, I expect when move on to the second API, the example shows there should have been the one that's assigned there (and not the modified and carried from the previous one) 

I then try the "read mode" and I find out that this issue doesn't seem to happen, the example will always refresh to its assigned.

Thank you in advance and any tips is welcome.

**Comment by mrin9** [comment]
thanks for the explanation and screenshots! 

I will look into it soon

**Comment by neildchen** [comment]
Hello mrin9; 

As of 2022-07-26 I tried on https://rapidocweb.com/examples/focused-mode.html again，and I assume the current rapi-doc v9.3.3 (https://github.com/rapi-doc/RapiDoc/releases/tag/v9.3.3) has been deployed as the rendering engine for the demo site. If following my steps as the above, the result is unchanged. Just want to make a note to you that this issue may have been overlooked. Thank you.

**Comment by mrin9** [comment]
> I assume the current rapi-doc v9.3.3 (https://github.com/rapi-doc/RapiDoc/releases/tag/v9.3.3) has been deployed as the rendering engine for the demo site.

No we use the edge/unreleased  - version on our demo site

@neildchen  We do not get notification on closed issues, so if an issue is closed and yet you find the fix is not what you expect it to be  please create a new issue and link the old one. Having said that I am not able to reproduce it. can you confirm if it is still an issue on your end ?

> PS: if you like to use the beta version then pick `rapidoc-min.js`  from the  `dist` folder  of this repo

**Comment by neildchen** [comment]
Hello Mrin9, 

Thanks for your response. I apologize caused you touble if any. I have tried again on the demo site and I believe that said issue has been resolved. 

Thanks again for your help.
