### ISSUE TITLE
Option to Hide "FILL EXAMPLE" Button

### ISSUE THREAD

**Issue by kashev** [rapi-doc/RapiDoc#731]
Our API doesn't have meaningful examples for us to populate in the schema, so we're interested in hiding the "FILL EXAMPLE" button:

<img width="1194" alt="Screen Shot 2022-04-21 at 7 39 30 PM" src="https://user-images.githubusercontent.com/2130609/164573878-af12a5c6-9509-4fa4-9c1b-1c8f54932613.png">

I looked through the [properties](https://github.com/mrin9/RapiDoc/blob/master/src/rapidoc.js#L45) and the [code](https://github.com/mrin9/RapiDoc/blob/master/src/components/api-request.js#L1018) and couldn't figure a way to hide the button.

**Comment by mrin9** [comment]
you should be able to hide it using `css-parts`

below is a non-tested code to give you an idea
```html
<html>
  ...
  <style>
    rapi-doc::part(btn-fill){ display: none; }
  </style>
  <rapi-doc  spec-url = "https://petstore.swagger.io/v2/swagger.json"> </rapi-doc>
  ...
</html>
```

**Comment by kashev** [comment]
Thank you! This worked perfectly. Closing out -- I think that this is just as easy as using dedicated property.
