### ISSUE TITLE
Issues migration

### ISSUE THREAD

**Issue by majoshi1** [rapi-doc/RapiDoc#739]
The rapidoc repo was migrated recently.  However, not sure how to locate issues created in old repos. Is it possible to tag original issue number and author to migrated issues?

**Comment by mrin9** [comment]
the migration should be transparent to locating issues. all the old issues have been migrated along with the repo and also the old issue links should continue to work. 

Can you point me to any old link thats not working ?  or any old issue that you are unable to locate in the new repo ?

**Comment by majoshi1** [comment]
Looks like migration was in progress yesterday. So, it was throwing 404 error. All good now. Sorry for false alarm.
