### ISSUE TITLE
Issue fixes

### ISSUE THREAD

**Issue by majoshi1** [rapi-doc/RapiDoc#741]
Following issues are marked as closed, but don't see the features in latest version. Tried these in 9.2.0. Any idea?
[602](https://github.com/rapi-doc/RapiDoc/issues/602)
[682](https://github.com/rapi-doc/RapiDoc/issues/682)
[686](https://github.com/rapi-doc/RapiDoc/issues/686)

Sorry for a duplicate issue. Will close once I get your answer.

**Comment by mrin9** [comment]
Fixing an issue is different from releasing it.

These issues could hav been fixed but not released. To test it out pick the unreleased version of rapidoc from `dist` folder

**Comment by majoshi1** [comment]
Any idea when these will be released?

**Comment by majoshi1** [comment]
Also where is ```dist``` folder?
