### ISSUE TITLE
How to get available tags and classes to write custom-styles.js and generate rapidoc-min.js

### ISSUE THREAD

**Issue by amandascm** [rapi-doc/RapiDoc#742]
I have been trying to generate `rapidoc-min.js` file with custom styles applied to `custom-styles.js`, as suggested in [this documentation of RapiDoc](https://rapidocweb.com/api.html) in the section about Advanced Styling - see also the screenshot below.
My question is: is there a way I can list all possible tags or classes and ids that may be used to style my OpenAPI docs rendering with RapiDoc? Is there an example of `custom-styles.js` with the use of more than few tags in the css content?

![image](https://user-images.githubusercontent.com/39717968/165810499-386edf2a-68c7-4eec-ab8b-e91ddb03e5ad.png)

**Comment by mrin9** [comment]
Sorry to reply bit late on this.

If you need to really update the styles inside of RapiDoc try using [`css-parts`](https://rapidocweb.com/css-parts.html)
xposed by rapidoc. 
It is recommended than the above approach. 
The documentation I pointed lists various css parts that you can override by your own styles and also you can avoid building your own copy of rapidoc on your end just for styling.

In case you are interested in changing a section in rapi-doc and not finding a corresponding css-part for it, let me know and I can see if I can expose it out for overriding

**Comment by janu1428** [comment]
HI Mrin,

If we have h2 tag inside section-operation part, can we add custom styles for them? In simple, can we add any styles for elements inside div if div conatins part attributes?

**Comment by mrin9** [comment]
No, with css parts you can not  target the children only the part that's exposed for styling, else it will defeat the purpose of style encapsulation.

In this particular case I will add more parts for you to be able to target the h2 tag as I see it may be a common need for many to style that section

**Comment by s-crypt** [comment]
would it be possible to get a part for links? When custom colors are involved, it is quite messy to change the colors of all the links in the different states (link, visited, hover, active) in the different sections (markdown, each part).
