### ISSUE TITLE
Examples in 9.2.0 are empty for most of our responses

### ISSUE THREAD

**Issue by cmars** [rapi-doc/RapiDoc#750]
We're using RapiDoc and noticed a regression from 9.1.3 -> 9.2.0. Examples are no longer showing for most of our request body and response content schemas.

For our latest beta API, https://api.snyk.io/rest/openapi/2022-04-06~beta:

9.1.3 shows a response example populated for `/orgs/{org_id}/projects` as:

![Screen Shot 2022-05-17 at 2 23 09 PM](https://user-images.githubusercontent.com/23741/168893738-eadbfd83-1ba8-4a07-be86-b92e51710659.png)

9.1.3 had some problems rendering our spec -- it seems to struggle with a `oneOf:` type union between a string and an object containing an `href:` property for example:

![Screen Shot 2022-05-17 at 2 23 20 PM](https://user-images.githubusercontent.com/23741/168893833-4db980a7-2979-4154-b76f-f5086e9f82fa.png)

However, 9.2.0 shows an empty drop-down for the same response:

<img width="801" alt="Screen Shot 2022-05-17 at 2 22 34 PM" src="https://user-images.githubusercontent.com/23741/168894018-731d4fef-bca3-4e44-9970-3aad854566b1.png">

Hopefully there is a simple fix here, it looks like some nice progress was made otherwise! Thanks!

**Comment by mrin9** [comment]
There is already a fix for this issue, but not yet release. When I test your spec using the latest codebase it looked fine

<img width="1472" alt="image" src="https://user-images.githubusercontent.com/5056899/168901421-6e8655ab-583b-4e1e-9f43-6c9e1082fce6.png">

To test this on your end with unreleased code use [`rapidoc-min.js`](https://raw.githubusercontent.com/rapi-doc/RapiDoc/master/dist/rapidoc-min.js) from `dist` folder

**Comment by cmars** [comment]
Good to know @mrin9! I'll look into depending on a recent commit hash until a release is available. Thanks!
