### ISSUE TITLE
Styles with wrapper class

### ISSUE THREAD

**Issue by janu1428** [rapi-doc/RapiDoc#755]
Hi,

I see there are more styles and few text fields which are hardcoded and not given option to overwrite.
Is there a possibility to wrap the styles in a class so that we can overwrite them in our code and it won't require change in rapidoc source code.

And also kindly let me know when the change related to operation method type block will be available. I can see it's currently available in beta version

**Comment by mrin9** [comment]
> I see there are more styles and few text fields which are hardcoded and not given option to overwrite.

That's on purpose. As as web-component we encapsulate styles not allow overrides. It helps in protection from style leaking from other components and allows you to have multiple RapiDoc webcomponent on the same page with its own styles.

If you want to target a specific section or component use[ `css-parts`](https://rapidocweb.com/css-parts.html)
and if you still dont find a part that you can style, let me know and we can decide if we can expose it  for user-styling
