### ISSUE TITLE
CDN is broken for 9.3.0

### ISSUE THREAD

**Issue by comphilip** [rapi-doc/RapiDoc#756]
`curl -L https://unpkg.com/rapidoc/dist/rapidoc-min.js` responses `Cannot find "/dist/rapidoc-min.js" in rapidoc@9.3.0`

**Comment by mrin9** [comment]
Thanks, 

`9.3.0` and `9.3.1` were suppose to be internal releases and shouldn't have been published to `npm`

We are unable to unpublish it as  it crossed more than 300 downloads

However we have now deprecated `9.3.0` release. 
Please use the release `9.3.2` 
Releases in github is fixed to reflect this change. 

Please create a new issue if there you are still facing this problem with the latest - `9.3.2` release
