### ISSUE TITLE
Wordwrap issues

### ISSUE THREAD

**Issue by murugaratham** [rapi-doc/RapiDoc#760]
Thanks for creating this wonderful tool, however, when we configure `schema-style="table"` `tr` height is too small to fit in long text.

<img width="726" alt="Screenshot 2022-05-31 at 11 04 00 AM" src="https://user-images.githubusercontent.com/653805/171084654-93bd557e-bb94-4325-bd39-c78019613fa3.png">

**Comment by mrin9** [comment]
Use the toggle on top-right to switch between single line or multiline description. If you always want to have schema description as multiline then use `schema-description-expanded = "true"` refer to our [API](https://rapidocweb.com/api.html#schema-description-expanded) for this 


![image](https://user-images.githubusercontent.com/5056899/171104094-ed77af75-ad73-4844-98c8-4f6d0c324bc7.png)

Feel free to close the issue if it solves your problem

**Comment by murugaratham** [comment]
sorry, i didn't notice that, thanks for helping
