### ISSUE TITLE
textarea for callbacks is small

### ISSUE THREAD

**Issue by alvin30595** [rapi-doc/RapiDoc#761]
The width for the callbacks is small for users to view, and the textarea is unable to resize horizontally

![image](https://user-images.githubusercontent.com/32334860/171182458-4358f496-46f7-4814-b140-444dc70eadcf.png)

**Comment by mrin9** [comment]
This has already been fixed as a part of this 091551eddc7ab6c6fb04b484629a24014c7fc25a commit

However not yet releases. To test it on your end use use [`rapidoc-min.js`](https://raw.githubusercontent.com/rapi-doc/RapiDoc/master/dist/rapidoc-min.js)  from `dist` folder
The test case for this can be be found at https://rapidocweb.com/examples/schema-read-and-write-only.html#post-user-hooks
