### ISSUE TITLE
Bug Report - Examples Pre-populating parameters

### ISSUE THREAD

**Issue by hansena** [rapi-doc/RapiDoc#762]
Expected Behavior:  parameter examples display as help text below the parameter field in the request pane and are used to populate request fields when the 'fill example' button is clicked.

Actual Behavior:
- array examples on array parameters pre-populate the field on load.
- boolean `true` examples pre-populate the field on load.
- boolean `false` examples do not appear as help text below the field.

Reproduction: 
```
{
  "openapi": "3.0.2",
  "info": {
    "title": "Minimum Reproduction"
  },
  "paths": {
    "/path": {
      "get": {
        "operationId": "get.path",
        "parameters": [
          {
            "name": "param1",
            "in": "query",
            "description": "string examples on array params operate as expected.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": { "type": "array", "items": { "type": "string" } },
            "example": "example"
          },
          {
            "name": "param2",
            "in": "query",
            "description": "array examples on array params un-expectedly pre-populate the field with the given value(s).",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": { "type": "array", "items": { "type": "string" } },
            "example": ["example1", "example2"]
          },
          {
            "name": "param3",
            "in": "query",
            "description": "boolean `true` examples un-expectedly pre-populate the field as well.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": { "type": "boolean" },
            "example": true
          },
          {
            "name": "param4",
            "in": "query",
            "description": "boolean `false` examples don't pre-populate the field, but they fail to render as an example.",
            "required": false,
            "style": "form",
            "explode": true,
            "schema": { "type": "boolean" },
            "example": false
          }
        ]
      }
    }
  }
}
``` 
![screenshot](https://user-images.githubusercontent.com/15346521/171633994-3ab06881-99ca-4aa2-b3e7-487832a58c39.png)

**Comment by mrin9** [comment]
First of all thanks for putting up a nice test case and the screenshots !!!

However there is a little misunderstanding on how the feature works

Here is what is expected
- if you specify an example for a parameter it will always be filled 
- if you do not want to fill the examples by default then set the attribute `fill-request-fields-with-example = 'false'`

Having said that, the feature is little buggy, which will be fixed

**Comment by mrin9** [comment]
here is the test case 
https://rapidocweb.com/examples/fill-example-test.html
