### ISSUE TITLE
Fill example overwrites all other examples

### ISSUE THREAD

**Issue by gmeister2** [rapi-doc/RapiDoc#763]
The 'fill example' action can overwrite all other examples.

version: 9.3.2

Procedure to reproduce:

- open docs (with render-style: focused)
- click on endpoint
- click on button 'clear'
- click on button 'fill example' -> example textarea shows correct data
- click on any other endpoint -> all other example textareas show the data that was created with the first 'fill example' action

**Comment by mrin9** [comment]
fixed by 21746a78f2feab5fed33f4cbcfc71b33b0d760d6
