### ISSUE TITLE
Is there a known page that dynamically receives a spec-url parameter?

### ISSUE THREAD

**Issue by swfsql** [rapi-doc/RapiDoc#767]
Hi, I just started studying the framework, and I'd like to know if is there a known page that can receive a spec-url query parameter and then use that parameter for setting up the spec-url that the rapidoc script uses. Would you know if is there any?

For example, for the spec url: https://raw.githubusercontent.com/OAI/OpenAPI-Specification/main/examples/v3.0/petstore.json
Perhaps a query parameter of `specurl` could receive a url-encoded information of that json file, that being: 
```https%3A%2F%2Fraw.githubusercontent.com%2FOAI%2FOpenAPI-Specification%2Fmain%2Fexamples%2Fv3.0%2Fpetstore.json```
..in such a way that the page would be able to render the rapidoc representation of that openapi file.

Originally my intention is to have github projects listing openapi files as some of their release artifacts and to be able to link to their rapidoc representation.

Thanks in advance!

---

Edit: this is related to a similar functionality from the swagger editor, such as in [this example](https://editor.swagger.io/?url=https://raw.githubusercontent.com/OAI/OpenAPI-Specification/master/examples/v3.0/petstore.yaml) (and I just noted that the value may not need to be url encoded).

**Comment by mrin9** [comment]
RapiDoc is a Web Component. You can place many RapiDoc element in a single page and they all can show different OpenAPI specs. 
Therefore it is not a good idea to automatically read `spec-url` from the  URL and apply it


Having said that. It is always possible for you to do it using little javascript

below is a code snippet to give you an idea how to do it. (not tested - check for syntax issues)

```html
<html>
...
  <rapi-doc id="the-doc" spec-url = "https://.../spec.yaml"> </rapi-doc>
  <script>
    window.addEventListener('DOMContentLoaded', (event) => {
      const queryString = window.location.search;
      const urlParams = new URLSearchParams(queryString);
      const queryStringSpecUrl = urlParams.get('spec-url')
      const rapidocEl = document.getElementById('the-doc');
      rapidocEl.setAttribute('spec-url', queryStringSpecUrl);
    });
  </script>
...
</html>
```

**Comment by swfsql** [comment]
Thanks @mrin9!  
I'd like to also ask you if the RapiDoc project would be interested in creating a webpage under it's domain (https://rapidocweb.com/) to specifically have a page with a single RapiDoc Web Component (similarly to the [examples](https://rapidocweb.com/examples/example2.html)) that would have the behavior that you just described?

(I'd be interested in using it, but perhaps this is not a popular or a reasonable demand)

**Comment by mrin9** [comment]
It shouldn't be much difficult. I will add an example soon

**Comment by mrin9** [comment]
below example takes you directly to a desired location (this is build in rapidoc without any javascript)
check out the `# path` you can get the path by looking into the html source 

https://rapidocweb.com/examples/focused-mode.html#get-/pet/-petId-
