### ISSUE TITLE
XML responses to try now aren't rendered in FireFox

### ISSUE THREAD

**Issue by colvinco** [rapi-doc/RapiDoc#770]
Related to #769

Using FireFox 101.0 (64-bit), XML responses result in the message `Response Status: (CORS or Network Issue)` without a response being rendered ![image](https://user-images.githubusercontent.com/51863265/172831415-c084a117-5878-491d-bffc-812aaf2a0448.png) even though the response was returned to the browser.

Repro steps:
1. Go to https://rapidocweb.com/examples/example1.html#get-/pet/findByStatus
2. Select `application/xml` as the response type in the Response Example section
3. Set `status` to `available`
4. Click try...

**Comment by mrin9** [comment]
closed by https://github.com/rapi-doc/RapiDoc/commit/6ee689f36d16e7485ad046c44ec4e7e2f669cb2d
