### ISSUE TITLE
Changing the background color of the filter bar

### ISSUE THREAD

**Issue by rahul7932** [rapi-doc/RapiDoc#773]
How can I change the background color of the filter bar?

**Comment by mrin9** [comment]
provide a screenshot which you are referring to filter bar. If we dont have a named `css-part` for it I can provide one and then you can use the `css-part` to style it

**Comment by rahul7932** [comment]
here is a screenshot

<img width="312" alt="Screen Shot 2022-06-19 at 4 52 06 PM" src="https://user-images.githubusercontent.com/52119279/174500039-4d33db81-264d-47b7-8ae0-a979bce55af0.png">

**Comment by mrin9** [comment]
```html
<style>
rapi-doc::part(section-navbar-search){
  background-color: red;
}
</style>
```

please use the `rapidoc-min.js` from `dist` folder to test it
