### ISSUE TITLE
Custom oauth redirect uri

### ISSUE THREAD

**Issue by emajo** [rapi-doc/RapiDoc#777]
When using the `OAuth2AuthenticationCodeFlow` retrieval form the `redirect_uri` is automatically detected by the library, it would be useful if a custom redirect_uri could be set.

In my case the path of the api reference is `{url}/api-reference`, the automatically detected redirect uri is `{url}/api-reference/oauth-receiver.html `, while the correct path would be `{url}/oauth-receiver.html`, so it is impossible to complete the oauth token retrieval process.

**Comment by mrin9** [comment]
what is the path for the `html` that contains the `<rapi-doc>` element

lets say it is `{url}/api-reference/index.html` then why would you not be able to create another `html` at that location {url}/api-reference/oauth-receiver.html` ?

If you still facing an issue with this then you can use `oauth-receiver` attribute to specify the path. This is an un-documented feature as we may change its behavior in later release

**Comment by emajo** [comment]
Hi, thanks for the response, I'm using rapidoc inside docusaurus, and if I put the `oauth-receiver` in the `api-reference` folder it will not be actually "served" at the `{url}/api-reference/oauth-receiver.html` url unfortunately.

I will try as soon as possible to use the `oauth-receiver` attribute so I can make it working.

Thanks again,
Emanuele

**Comment by mrin9** [comment]
okay let me know if you were able to solve it using `oauth-receiver` this will help us decide should this attribute be made public

**Comment by emajo** [comment]
Yes, using `oauth-receiver` it works!

**Comment by aminya** [comment]
@mrin9 I created the `oauth-receiver.html` file and served it, but when Auth0 redirects back, the tokens are not read by Rapidoc. Do I need to anything else?

**Comment by wparad** [comment]
> @mrin9 I created the `oauth-receiver.html` file and served it, but when Auth0 redirects back, the tokens are not read by Rapidoc. Do I need to do anything else?
> 
> See this for more information: [juhaku/utoipa#886](https://github.com/juhaku/utoipa/issues/886)

Does it also not work if you switch to this [one](https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#openapi-explorer)?

**Comment by aminya** [comment]
@wparad Thanks for the link. I'll check out the project. It's a bit hard for me to try that now as I use RapiDoc through Rust Actix. I can build the project and serve it myself, but it needs more work.

**Comment by wparad** [comment]
@aminya If there is something stopping you from serving it through Actix, just file a ticket in the repo and someone can try to take a look. I can't imagine there would be a problem there, but the devil is always in the details.
