### ISSUE TITLE
Hiding "Authentication" tab

### ISSUE THREAD

**Issue by rahul7932** [rapi-doc/RapiDoc#778]
I want to hide the "Authentication" tab. How can I do this?

<img width="204" alt="Screen Shot 2022-07-03 at 3 32 21 AM" src="https://user-images.githubusercontent.com/52119279/177029923-667a8313-2681-463d-a9cc-78a722f8a720.png">

**Comment by mrin9** [comment]
refer to our [API](https://rapidocweb.com/api.html#att-sections) for this
