### ISSUE TITLE
JsonSchemaViewer does not respect showSideNav attribute.

### ISSUE THREAD

**Issue by nnaku** [rapi-doc/RapiDoc#781]
I'm trying to inject following html to tag description. Theme and header attributes works as expected but I cannot hide the side nav. 

```html
<json-schema-viewer
  spec-url="data:;base64,;..."
  theme="light"
  show-header="false"
  show-side-nav="false">
</json-schema-viewer>
```

And why? Well, we have websocket on same server and I like to just list event payloads in description. Keeping all the stuff in same apidoc feels better than docs scattered all over the places.

**Comment by nnaku** [comment]
> OpenAPI do not support documenting WebSocket. So unfortunately you cant

Well, I didn't suggest or ask for WebSocket support. I'm just asking if it's possible to render any json schema to the description.

> `json-schema-viewer` is not yet made public nor we provide any documentation or usage example for this component. It is intended to show certain schema documentations that are loosely based on `json-schema` spec, such as MongoDB / DocumentDB, Elasticsearch / OpenSearch, Avro Schema etc.

If you have intend to publish a <json-schema-viewer> component in the future. 
Let this be feature request or wish. 😅

**Comment by mrin9** [comment]
okay I will add this to our queue as a feature request. to allow usage of `json-schema-viewer` component inside of the `rapi-doc` component in a more structured way

**Comment by shishkin** [comment]
@nnaku how were you able to pass the schema via the data URL? I'm trying the same and getting error `RapiDoc:  There was an issue while parsing the spec` with:

```js
{
  errors: [],
  resolvedSpec: { /* my correctly decoded json schema */ },
  spec: {}
}
```

**Comment by nnaku** [comment]
@shishkin here is how i got it working.  Its from internal tool so no live example sorry...

```js

const markdownTemplate = ({title, description, spec}) => `
### \`${title}\`

${description}

<div class="event-schema" style="height: auto;">
  <json-schema-viewer 
    spec-url="data:;base64,${Buffer.from(JSON.stringify(spec), 'utf8').toString('base64')}" 
    theme="light" 
    show-side-nav="false" 
    show-header="false" 
    show-info="false" 
    allow-search="false" 
    allow-advanced-search="false">
  </json-schema-viewer>
</div>
`
```

**Comment by shishkin** [comment]
OK, after some debugging it seems the issue I had wasn't with the base64 data URL encoding, but with the expected spec format. From [this mongo example](https://github.com/rapi-doc/RapiDoc/blob/34d4d0015b12cf47fced51b03390f9bd1dce2f71/docs/examples/mongo.html#L31) and the [parser logic](https://github.com/rapi-doc/RapiDoc/blob/34d4d0015b12cf47fced51b03390f9bd1dce2f71/src/utils/spec-parser.js#L18-L29) I see that `json-schema-viewer` expects some weird structure like:

```yaml
jsonSchemaViewer: 1.0.0
schemaAndExamples:
  // real schema goes in here
```

Is this some kind of standard? Can the `json-schema-viewer` just accept a plain JSON schema as input?

**Comment by mrin9** [comment]
it isnt any standard those are the sections reserved for the component and in future there may be additional sections added.  just accepting a json is too limiting
