### ISSUE TITLE
Feature request: Display schema name

### ISSUE THREAD

**Issue by aarjithn** [rapi-doc/RapiDoc#782]
In OpenAPI Swagger UI, it is possible to view name of a Schema. This is very useful for us to define Type definitions in TypeScript.

Collapsed view

![image](https://user-images.githubusercontent.com/10304259/178199668-1a268c36-168a-4482-9e96-f8e3d5995b58.png)

Expanded view

<img width="764" alt="image" src="https://user-images.githubusercontent.com/10304259/178200324-7420886d-1247-4469-8708-27211c7820e1.png">

Rapidoc however shows the expanded JSON structure, and not Schema name itself. 
The name is not displayed even if object is collapsed. Is there a way to show the Schema name?

<img width="655" alt="image" src="https://user-images.githubusercontent.com/10304259/178199946-eec0e3c1-d372-482d-b500-b34da2fc8e32.png">

**Comment by mrin9** [comment]
SchemaName is very internal to the spec. We dont think it brings in much value to a reader of the document. Instead we opted to show a more cleaner and less noisy view of the Schema.

If you can provide me some compelling reason for an API user (not a spec developer) to know about Schema Names used inside the spec I will take it forward to the discussion table

**Comment by aarjithn** [comment]
Agree that if you are just calling the API as json it is not much of value.

It is useful for us because we try to keep the Typescript types in sync with the Schema name so that same schema type gets reused across multiple APIs. 

It can be an option which is disabled by default, but I believe it is useful for UI Developers who use Typescript to type the responses. 

Ofcourse it won't be required if one is auto-generating d.ts from openapi yaml files, but in my experience that is not common as manual typing.

**Comment by mrin9** [comment]
We do have seen schemas composed of many other schemas, which will result into having these names embedded in between too and not just at the top. The other challenge is when you have to show a complex composition made with `one-of` , `any-of` constructs both in terms of space usage on narrow screen devices.

I will take it further to discuss with the team let see what they have to say about this

**Comment by Igreh** [comment]
+1 for feature

**Comment by mrin9** [comment]
closing this request as we did not receive enough traction on this. However if I get a PR. I can test and move it forward for an approval
