### ISSUE TITLE
Fill example overwrites all other examples - same issue

### ISSUE THREAD

**Issue by gmeister2** [rapi-doc/RapiDoc#784]
The 'fill example' action (example in Request section) still seems to be able to overwrite all other examples.
See #763 for original issue report.

version: 9.3.3
render-style: focused

Procedure to reproduce:

- open docs
- click on endpoint
- click on button 'clear'
- click on button 'fill example' -> example textarea shows correct data
- click on any other endpoint -> all other example textareas show the data that was created with the first 'fill example' action

Also, unrelated to the above:
Would it be possible to clear the response textarea (response in Request section) to its default state (i.e. empty) when switching endpoints. The lingering response data from a previous endpoint could be confusing when looking at a new endpoint.

**Comment by mrin9** [comment]
can you provide me a spec for it ?

**Comment by gmeister2** [comment]
I can reproduce it with this demo page (from the examples):

- open docs -> https://rapidocweb.com/examples/focused-mode.html
- click on endpoint -> 'Add a new pet to the store'
- click on button 'clear'
- click on button 'fill example' -> example textarea shows again the correct data, in this case an object
- click on other endpoint -> 'Creates list of users with given input array' -> example textarea shows incorrect data, it is the previous object, the original example for this endpoint was an array

**Comment by mrin9** [comment]
thanks will take a look at it

**Comment by mrin9** [comment]
can you confirm with the latest changes, it works as you are expecting ?

**Comment by gmeister2** [comment]
I tested the demo page (https://rapidocweb.com/examples/focused-mode.html):

- 'fill example' action only updates the current endpoint :heavy_check_mark:
- when switching endpoints, the response textarea (response in Request section) gets cleared :heavy_check_mark:

These solve my issue, thank you!
