### ISSUE TITLE
how to modify api request.body

### ISSUE THREAD

**Issue by nitinmcsam** [rapi-doc/RapiDoc#788]
rapidocEl.addEventListener('before-try', (e) => {
  if (e.detail.request.method === 'POST') {
    e.detail.request.headers.append('my-header', 'XYX');
  }
})

how to modify request.body

**Comment by mrin9** [comment]
rapidoc exposes[ native request object ](https://developer.mozilla.org/en-US/docs/Web/API/Request) of HTML.
you can you any method/properties available to interact the the object. 

However body is a `read only` property so you cannot modify it
