### ISSUE TITLE
Navigation active only on double click

### ISSUE THREAD

**Issue by gil-fitussi** [rapi-doc/RapiDoc#789]
Hi, thanks for amazing lib.

There is a bug when the render-style is focused and navigation bar item active only when double click.

For example:
https://www.linkpicture.com/q/Annotation-2022-07-26-203842.png

Thanks

**Comment by mrin9** [comment]
thanks for reporting. Fixed by 403b5500e0e98a00331bf45429e3a334c4bc2c1e
