### ISSUE TITLE
[Feature Request] List of all schema

### ISSUE THREAD

**Issue by AlexanderHawliczek-InterhomeGroup** [rapi-doc/RapiDoc#790]
First of all thank you for your great work. 👍

We are missing a feature that was very helpful and is available on swagger-ui.
Swagger provides a list of all data schema including not referenced items at the bottom.

In our case we have enums with a lot of values that can change without further notice.
To keep generated clients stable (not trying to parse new unknown values), we leave these fields as plain string rather then being of an enum type.
For the purpose to show a complete documentation, we would like to show these within rapi-doc viewer.
Is that possible?
Did I miss this feature somewhere?

Would be great if we could somehow reference these schemas from other places too. (description of endpoints, other schemas, ...)

Thank you

**Comment by mrin9** [comment]
> Did I miss this feature somewhere?

use `show-components="true"`
refer it in our [API](https://rapidocweb.com/api#att-sections)

**Comment by AlexanderHawliczek-InterhomeGroup** [comment]
arr, sorry
I wasn't trying with the focused style
thank you a lot
