### ISSUE TITLE
Feature Request: Allow to use a new request in before-try event handler

### ISSUE THREAD

**Issue by IanSun** [rapi-doc/RapiDoc#791]
Currently, before-try event provides a `Request` object and use that object to make a request.
It's impossible to modify the body and the query of the request for now because of these properties are read only.

Background is, I want to make a request with [arbitrary query strings](https://github.com/OAI/OpenAPI-Specification/issues/1502). This hasn't been supported by current spec. I tried to set the parameter key to an empty string according to [this comment](https://github.com/OAI/OpenAPI-Specification/issues/1502#issuecomment-371203508). RapiDoc renders well. However, it stills prepend the `=` symbol when I click "Try". I know that is a correct behaviour but what I hope is to provide a way to modify the url to meet my design.

**Comment by mrin9** [comment]
Update: we are still discussing this use-case as we like to take care of some of our own use-cases

**Comment by mrin9** [comment]
You may now update/append `url, url-params, method, request-body, headers` in  `before-try` event. For more info/usage check our API section.
 
> The feature is still experimental , collecting our user feedback on this

**Comment by alex-albericio** [comment]
We need to replace the url for a special use case. I've tested the new code at it works as expected (although I had to change the version in package.json from 9.3.4.beta to 9.3.4-beta.0 because npm complained with invalid version).

@mrin9 do you plan to include this feature in the next release? Any ETA for that?
