### ISSUE TITLE
Can't pass array server-url

### ISSUE THREAD

**Issue by BorisBurbon** [rapi-doc/RapiDoc#792]
I can pass array  - server-url = ['http://swagger.io', http://swagger.io] but in documentation I will see http://swagger.io,http://swagger.io
if I pass [{url: "http://swagger.io" }, {url: "http://swagger.io" }] I will see [object Object],[object Object]

How will I can get list server urls"? For example

 - http://.....
 - http://......

**Comment by mrin9** [comment]
`server-url` attribute cannot take multiple values. It is just to specify a single server. 
`server-url` is not a recommended way to specify API Server. we provided it as a quicker way to test your spec. 

read more about it in our [API](https://rapidocweb.com/api#att-server) section.

If you are dealing with multiple API server then consider specifying it in the spec. RapiDoc will list all those API servers, this will also help you not get locked with RapiDoc as `server-url` is proprietary to RapiDoc using OpenAPI spec to sepcify servers will allow you to use other document renderers like Swagger UI 

you can checkout this example https://rapidocweb.com/examples/server-vars.html#get-/api-server-template
