### ISSUE TITLE
rapidoc-min.js contains syntax errors

### ISSUE THREAD

**Issue by Shryne** [rapi-doc/RapiDoc#794]
I have an application that uses rapidoc-min.js from https://unpkg.com/rapidoc/dist/rapidoc-min.js.
Version 9.2.0 worked fine but 9.3.2 and 9.3.3 result in an empty page.

According to Firefox the error seems to be this:
> Uncaught SyntaxError: expected expression, got ')' (2, 9012)

Here is the code:
```js
for (const t of n.getAttributeNames()) if (t.endsWith("$lit$") || t.startsWith(w)) {
    const r = c[o++];
    if (e.push(t), void 0 !== r) {
        const e = n.getAttributer.toLowerCase() + "$lit$"
    ). // here is the bug. The bracket is wrong
        split(w), t = /([.?@])?(.*)/.exec(r);
        s.push({
            type: 1,
            index: a,
            name: t[2],
            strings: e,
            ctor: "." === t[1] ? K : "?" === t[1] ? Y : "@" === t[1] ? Z : G
        })
    } else s.push({type: 6, index: a})
}
```
However, fixing this isn't enough. This is the next error I get:
> Uncaught SyntaxError: missing variable name

IntelliJ even shows me about 60 syntax errors.

**Comment by mrin9** [comment]
I have to verify that. meanwhile can you pick the minified js from dist folder in github and verify that works for you

**Comment by Shryne** [comment]
The dist version does work. Thanks :)

**Comment by mrin9** [comment]
closing it as `9.3.4-beta` works
