### ISSUE TITLE
Unable to parse JSON examples response when it contains specific values

### ISSUE THREAD

**Issue by Polders** [rapi-doc/RapiDoc#796]
Hello,

We discovered that while many of our response examples are correctly parsed and displayed in tree form with syntax highlighting, some of them default to text. 

An example like this one
```json
{ "textWithSingleQuote": "let's say this is my text" }
```
or this one
```json
{ "isoDate": "2022-08-08T00:00:00.000Z" }
```
will both default to text despite being valid JSON (the second one is especially important to us because we have a lot of dates)

After reading your sources, I believe the cause to be a line in schema-utils.js, in `generateExample()` where there is an attempt to "fix" the JSON string by replacing values according to two regex that happen to match the text in my examples above.

It seems like this is trying to fix invalid JSON without proper double quotes into correct JSON, but it breaks valid JSON in the attempt. Also weirdly this doesn't happen when using the example attribute instead of the examples plural.

Other than that Rapidoc rocks, thank you for this awesome piece of software and have a nice day.

**Comment by mrin9** [comment]
thanks for reporting, will take a look at it
