### ISSUE TITLE
css-file option in conjunction with render-style="view" option injects multiple <link> tags

### ISSUE THREAD

**Issue by james-marshall** [rapi-doc/RapiDoc#801]
Hi there,

I'm trying to use the RapiDoc plugin with the option `render-style="view"` with the `css-file` option to use an external CSS file. Every time I click and expand a method (`part="section-endpoint`) it injects a new `<link>` tag linked to the specified `css-file` after the `<div id="the-main-body">` element, and they keep building up causing performance issues. It doesn't seem to do this with `render-style="read"`

Is there an issue there? 

Many thanks

![Capture](https://user-images.githubusercontent.com/4730568/184693575-a8d216c4-1d0b-427f-bb5e-7d8df4e47297.PNG)

**Comment by mrin9** [comment]
I will look into this issue. 
but if possible you should move away from `css-file` approach to style RapiDoc instead use 
[`css-parts`](https://rapidocweb.com/css-parts.html)

with css parts we expose various parts of RapDoc which you can style just as you you would style a regular html doc. we expose many parts today for them to be styled independently. 

go through our documentation on css parts and try to style the needed parts of your documentation. we will soon be deprecating `css-file`.

if you need any specific section to be styled and not finding it in css-parts let us know and we can see if that can be exposed for user styling

**Comment by james-marshall** [comment]
Thank you so much.

The only element I really need access to change styles is this one which wraps the request buttons. I'm finding the inline `display: flex` causes the layout to not be 100% responsive (buttons overlap the edge). I think this is due to being inside a layout that's not 100% width because of the left hand menu on my page. If I had the ability to change that `display: flex` the layout would be perfect.

![screenshot](https://user-images.githubusercontent.com/4730568/184831728-7b5304bf-2a6e-46c9-8fc5-fa32361b871b.png)

If I could change that element then I could probably just use `css-parts` for the styling to fit my needs, as the encapsulated styling is really good.

**Comment by mrin9** [comment]
added css-part `wrap-request-btn` in order to test it please use `rapidoc-min.js` from dist folder
