### ISSUE TITLE
Remove the completely unnecessary profanity from markdown-headings.yaml

### ISSUE THREAD

**Issue by ianjevans** [rapi-doc/RapiDoc#802]
While I don't really have any particular moral or ethical problem with using profanity, it's not appropriate in all contexts. It's especially not appropriate to use it in a project's documentation, and I say that as technical writer for 25 years.

We're evaluating Rapidoc at Cockroach Labs and I was about to send [a link on customizing section headings in the output](https://rapidocweb.com/examples/markdown-headings.html#overview--how-to-use-apis) to a coworker when I saw the content of the example. The profanity and odd personal references are unnecessary, unprofessional, and more than a little off-putting. It's kind of amazing it's [been there for over two years](https://github.com/rapi-doc/RapiDoc/blame/master/docs/specs/markdown-headings.yaml). Whether or not I'm offended by it (I'm not), I can't make that judgement for the people I work with. 

Edit: I just now noticed the really gross sexist stuff further down the page, which actually does offend me. I absolutely would not use these docs in any professional capacity.

There's so many better ways of showing the feature than what is currently in the repo.

**Comment by mrin9** [comment]
I do understand the particular example may not be well suited for all audiences. 
Please go ahead submit your PR to change that example that you think can better represent the feature and I should be able to get it through the approval

**Comment by ianjevans** [comment]
I don't feel like that is an acceptable answer to this issue.

**Comment by mrin9** [comment]
not sure what were you expecting as an answer. I did agreed with your opinion on this. Is there anything that I am missing out ?

**Comment by ntotten** [comment]
I created two pull requests that I think help with this issue:

1. Corrects the immediate problem example: https://github.com/rapi-doc/RapiDoc/pull/803
2. Adds two linting tools (inclusive language & profanity) that run on pull requests to help catch these types of contributions in the future: https://github.com/rapi-doc/RapiDoc/pull/804

**Comment by mrin9** [comment]
closed by #803
