### ISSUE TITLE
Headers from a redirected request are not displayed in the response

### ISSUE THREAD

**Issue by erendogan51** [rapi-doc/RapiDoc#807]
I have an endpoint which searches for AWS s3 bucket objects and, if present, returns a redirect to a pre-signed url for the object. My problem is that the response headers of such redirect are not displayed in the response container of RapiDoc. This is particularly annoying, because the Content-Disposition header is ignored. RapiDoc correctly inrefers the response body and prompts a download button, but the filename, which is set in the header, is being ignored.

The headers displayed:
![image](https://user-images.githubusercontent.com/93084571/186398537-6e446c25-5607-4843-a618-4b04b5ae3041.png)

The headers of the redirect:
![image](https://user-images.githubusercontent.com/93084571/186400244-4c5d9d83-475e-4951-ae64-d78a5e0fd6f0.png)

**Comment by mrin9** [comment]
There are restriction to access response headers using scripts running on the browser. You may see them in Browsers -Developer Tools but can access them through scripts unless you allow them specifically on your server through `access-control-expose-headers`

https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Expose-Headers

**Comment by erendogan51** [comment]
my bad, thank you very much :)
