### ISSUE TITLE
Feature request: Management of externalDocs in paths 

### ISSUE THREAD

**Issue by lequant40** [rapi-doc/RapiDoc#809]
Hello,

As per title, it seems the externalDocs porperty is not managed yet by RapiDoc.

Link to a example: https://github.com/OAI/OpenAPI-Specification/blob/main/examples/v2.0/json/petstore-with-external-docs.json#L38

Screenshot of what it looks like in Swagger:
![image](https://user-images.githubusercontent.com/16731716/187651760-291c74b4-dc66-463e-a6ef-a3e7033dcef6.png)

Thanks a lot for what you are doing!

Cheers,

Roman

**Comment by mrin9** [comment]
I will check it out, but you can always provide the links to your external docs in the description as well using markdown syntax

**Comment by lequant40** [comment]
Yeah, fully agree with this - this is more a nice to have (since a standard field is there for this) than something that cannot be done otherwise.

Thanks!

**Comment by rberger** [comment]
`externalDocs` is in OpenAPI 3.0 and 3.1 standard.  Makes it a bit awkward to have it used by other tooling and then do something special for rapidoc. This is the first issue I've seen like this with rapidoc, which otherwise has been fantastic.

**Comment by lequant40** [comment]
Top, thanks!
