### ISSUE TITLE
Multiline descriptions are duplicated when multiline is enabled

### ISSUE THREAD

**Issue by sbingner** [rapi-doc/RapiDoc#811]
When you have a multiline comment it does not render well in the schema, and gets duplicated when expanded to multiline.

Example image showing the issue in multiline mode: ![image](https://user-images.githubusercontent.com/354533/187878582-cd295901-2b65-4bd8-860c-ea22e1efe2f2.png)

And single-line mode: 
![image](https://user-images.githubusercontent.com/354533/187878821-906542e7-196b-40aa-9195-aa6495a32cfc.png)

Example .json (in zip so I could upload it) that duplicates this issue: [openapi-example.zip](https://github.com/rapi-doc/RapiDoc/files/9468538/openapi-example.zip)

**Comment by mrin9** [comment]
thanks for reporting, I will work on it soon

**Comment by mrin9** [comment]
to test it use `rapidoc-min.js` from `dist` folder of this repo
