### ISSUE TITLE
ReadOnly object within oneof being displayed within schema for update requests

### ISSUE THREAD

**Issue by AlaNDGT** [rapi-doc/RapiDoc#812]
**Version**: 9.3.3

**Description**:

When using `oneof` with direct objects having readonly behaviour, it's being displayed.

But when referencing a schema with readonly object, it does not show up.

Here's a screenshot comparing both behaviour:

![image](https://user-images.githubusercontent.com/3120817/188288425-ca471b8d-74e2-40cd-8745-34b0f72a1c7f.png)

**Additional**:

**Would be great if we could completely hide `oneof` fields which have only `readonly` schemas/objects?**

**Example OAS**:

```yaml
openapi: 3.1.0
info:
  title: sample
  version: '1.0'
servers:
  - url: 'http://localhost:3000'
    description: test
paths:
  /test:
    post:
      summary: Create
      operationId: post-test
      responses:
        '201':
          description: Created
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Test'
            examples: {}
        description: ''
      description: ''
    parameters: []
components:
  schemas:
    Test:
      title: ''
      type: object
      description: ''
      examples: []
      x-tags:
        - test
        - user
      properties:
        direct:
          oneOf:
            - properties:
                foo:
                  type: string
              behavior: Read Only
            - properties:
                bar:
                  type: string
              behavior: Read Only
          type: object
        reference:
          oneOf:
            - $ref: '#/components/schemas/Foo'
            - $ref: '#/components/schemas/Bar'
    Foo:
      type: object
      title: Foo
      properties:
        foo:
          type: string
      readOnly: true
    Bar:
      type: object
      title: Bar
      properties:
        bar:
          type: string
      readOnly: true
```

**Comment by mrin9** [comment]
can you replace `behavior: Read Only` -> `readOnly: true`  in your sample spec ?

**Comment by AlaNDGT** [comment]
Ah my bad, did not noticed. Seems to be same now with `readOnly: true`

Is it possible to completely hide `oneof` which contains only read only schemas?

**Comment by mrin9** [comment]
we do an incremental construction of the schema, to achieve what you are asking will need us a big refactoring of the way these views are generated and event bigger testing effort to pass through various test cases. I do not see the much of a value add for the effort needed. therefore will close this issue. However I am open to PRs if you or anyone interested like to make an effort

**Comment by mrin9** [comment]
Since we decided to include a breaking change elsewhere, so we might as well revisit this
