### ISSUE TITLE
It is not possible to navigate to the tag description page when on-nav-tag-click="expand-collapse"

### ISSUE THREAD

**Issue by smai-f** [rapi-doc/RapiDoc#823]
We load our endpoints with all of the tags collapsed using the `x-tag-expanded: false` property.

When `on-nav-tag-click="show-description"`, we do not like that the user has to click specifically on the arrow to expand whereas the header navigates to the tag description - it seems like the user might not discover the endpoint expansion functionality and would just assume that the tag description page is all there is.

Thus we prefer the `on-nav-tag-click="expand-collapse"` option, because clicking anywhere on the tag header area will expand the tag and show the endpoints.

However, when `on-nav-tag-click="expand-collapse"`, it doesn't seem like it's possible to ever get to the tag description because _no_ part of the header links to the tag description page. 

- Is there any other way to navigate to the tag description page?
- Would it be possible perhaps to update the functionality so that the tag text always links to the description page when both options are enabled? Perhaps by setting a click handler on [this](https://github.com/rapi-doc/RapiDoc/blob/master/src/templates/navbar-template.js#L163) to always scroll to event target?

Thank you for a great project!

**Comment by mrin9** [comment]
lemme make sure what's the ask is here.

On click of a `TAG` Are you expecting it should expand and also show the description on the right side ?

**Comment by smai-f** [comment]
@mrin9 I was thinking more like if `expand-collapse`, all the area in green would expand/collapse, and clicking the text (area in blue) would show the description on the right side:

![image](https://user-images.githubusercontent.com/5832646/190691396-1794e0fc-b6b0-47a0-9876-e7861d06efac.png)

Or another idea would be to keep this option the same so we can use `expand-collapse`, but add another option like `render-description-node` that if true, would insert a "Description" node at the top of the list of endpoints that one could click to see the tag description? I like that better as it makes it the most explicit the Description exists. But I reckon a lot more work to implement.

**Comment by mrin9** [comment]
well we would like to keep fixed click targets from the usability PoV. 

We have seen tags containing 10 word sentences as well. 
In those cases some tags will have large expand/collapse click area and some tags will have only the arrow  to be clicked. this will be ambiguous to a user.

I have forwarded this problem to our UX team, lets see what they come up wid

**Comment by mrin9** [comment]
Now provided a way to view tag description in focused mode with tag click set to expand/collapse.

We are still subtle here in our approach where we just display an icon which work as a toggle to expand/collapse the Tag Description. `focused` rendering style was created so that it focuses only on a single operation at a time to minimize any distraction therefore we will be maintaining the same experience.

you can check the preview below. If you like to test it at your end please pick up the beta version `rapidoc-min.js` from `dist` folder of this repo

![image](https://user-images.githubusercontent.com/5056899/190885271-554696dc-470e-4926-babd-7d1db4f56348.png)

**Comment by majoshi1** [comment]
I have [forked](https://www.npmjs.com/package/@majoshi1/rapidoc) rapidoc to change the behavior of `navigate` to do both of the following:
- Toggle `expand/collapse` .
- Show tag description.

Needs `on-nav-tag-click="show-description`.

**Comment by wparad** [comment]
@majoshi1 i'm pretty sure the for at [OpenAPI Explorer](https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#beautiful-and-responsive-api-explorer-and-console) already does this.

**Comment by majoshi1** [comment]
Thanks @wparad for your comment. I checked [OpenAPI Explorer](https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#beautiful-and-responsive-api-explorer-and-console). I tried [this](https://rapidocweb.com/specs/petstore_extended.yaml) sample pet store yaml in their [demo](https://authress-engineering.github.io/openapi-explorer/).  It _does_ expand/collapse by default. But does _not_ show tag description. Also checked [docs](https://github.com/Authress-Engineering/openapi-explorer/blob/release/2.2/docs/documentation.md) for any custom configuration. But only thing they have is `use-path-in-nav-bar`.

**Comment by wparad** [comment]
I know most of the configuration for dynamic stuff like that can be controlled directly in the spec configuration using the `OnSpecLoad` event. If the tag description is part of the spec and it isn't being display, that sounds like a bug and I suggest reporting it, so it can get fixed.

**Comment by majoshi1** [comment]
Raised [this](https://github.com/Authress-Engineering/openapi-explorer/issues/255) issue with [OpenAPI Explorer](https://github.com/Authress-Engineering/openapi-explorer?tab=readme-ov-file#beautiful-and-responsive-api-explorer-and-console). 
As such, [here](https://majoshi1.github.io/rapidocweb/examples/focused-mode.html#tag--pet) is the working example in the [forked](https://www.npmjs.com/package/@majoshi1/rapidoc) rapidoc.
