### ISSUE TITLE
Object with `oneOf` does not support property with type object

### ISSUE THREAD

**Issue by diogotcorreia** [rapi-doc/RapiDoc#825]
### Bug Description

The following schema produces the output below:

```yaml
openapi: "3.1.0"
info:
  title: Example
  version: "1.0.0"
servers:
  - url: https://example.com
paths:
  /test:
    get:
      summary: Example
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Parent"

components:
  schemas:
    Parent:
      type: object
      properties:
        a:
          type: object
          properties:
            name:
              type: string
      oneOf:
        - $ref: "#/components/schemas/Child1"
        - $ref: "#/components/schemas/Child2"
    Child1:
      type: object
      properties:
        b:
          type: string
    Child2:
      type: object
      properties:
        c:
          type: string
```
![image](https://user-images.githubusercontent.com/7467891/190833133-c78b2868-7603-4c1d-838c-40ee568d21e9.png)
![image](https://user-images.githubusercontent.com/7467891/190833147-5f1df24e-6210-4d36-8c6b-6a7f8345ba40.png)

There are two issues:
- On the "Example" tab, there is no example of the `a` property (it's displayed as `?`)
- On the "Schema" tab, the property key (`a`) is not shown, only the schema of the value

### Expected

The two problems above should not happen:
- The example should be something like
  ```json
  {
    "b": "string",
    "a": {
      "name": "string"
     }
   }
   ```
- The schema should be something like
  ```
   a: {
     name: string
   }
   ONE OF
   1 {
   b: string
   }
   2 {
   c: string
   }
   ```

### Other Information

Almost all (check below) other non `type: object` properties work fine, it's only when `type` is `object`.

When there is a property with `type: array`, if the items are not of type `object`, only the example problem occurs.
If the items are of type `object`, then both problems occur.

If we replace `oneOf` with `anyOf`, examples are correctly generated, but the schema problems still occur.

I've validated the schema with `swagger-cli` and it said it's valid.

ReDoc handles this situation correctly, as it can be seen below.
![image](https://user-images.githubusercontent.com/7467891/190833801-23214412-8960-40e1-ad3d-ff6a5dae5ddd.png)

### Workarounds

None that I know of

**Comment by mrin9** [comment]
thanks for pointing, it should be working fine now. 
below are some test cases 
- https://rapidocweb.com/examples/xxx-of-nesting-with-expand-level.html
- https://rapidocweb.com/examples/oneof-combinations.html
- https://rapidocweb.com/examples/oneof.html

if you like to try on your end, please pick up the beta release `rapidoc-min.js` from `dist` folder in this repo
