### ISSUE TITLE
Scherma property type "string" gets rendered incorrectly when followed by enum

### ISSUE THREAD

**Issue by DanielaGordas** [rapi-doc/RapiDoc#826]
Hi @mrin9,

When the property type is `string` and it is followed by a list of `enum` the type gets incorrectly rendered in the schema as `enum` instead of `string` like in the example below:

<img width="449" alt="Screenshot 2022-09-20 at 10 26 21" src="https://user-images.githubusercontent.com/80751048/191207961-9f636af9-12fb-4709-b2df-7cd5a1b28976.png">

<img width="887" alt="Screenshot 2022-09-20 at 10 12 24" src="https://user-images.githubusercontent.com/80751048/191208174-f5407c21-70b8-4eaa-9ff1-575622fc5fbd.png">

Using `openapi: 3.1.0`

I was wondering if there is any quick fix for this? Thanks in advance!

**Comment by mrin9** [comment]
this is more of a feature than a bug. When the schema has more than just the `type`  such as `enum`, `format` or is it `nullable` etc, we prefer showing more specific one. This is what we found is desired in most cases. 

![image](https://user-images.githubusercontent.com/5056899/191283978-7ef29a82-e6da-420f-b56e-3f9777ef9f51.png)

**Comment by DanielaGordas** [comment]
Thanks for the quick reply and for the explanation. I can see why that's preferred in many of the cases listed.

Is there any workaround to still display the type as `string` but also use the `enum` to list the allowed options?

Thanks!

**Comment by mrin9** [comment]
there is none at the moment. 
I have added this question in our next internal user-survey. will keep this issue it open for some time for our community user to vote on it

**Comment by mrin9** [comment]
closing as we did not get much traction on it
