### ISSUE TITLE
[Feature Request] a class or way to style the "selected" path option

### ISSUE THREAD

**Issue by WilliamStam** [rapi-doc/RapiDoc#827]
right now (unless im totally useless) i cant seem to find a way to style the "selected" path when in focused mode
```
<rapi-doc
    spec-url="/openapi.yaml"
    persist-auth="true"
    theme="light"
    header-color="#ffffff"
    primary-color="#ff8300"
    show-method-in-nav-bar="as-colored-block"
    use-path-in-nav-bar="true"
    nav-bg-color="#f1f1f1"
    nav-text-color="#444444"
    nav-accent-color="#444444"
    layout="row"
    render-style="focused"
    show-header="false"
    allow-spec-url-load="false"
    allow-spec-file-load="false"
    allow-spec-file-download="false"
    allow-search="false"
    allow-advanced-search="false"
    show-info="true"
    allow-server-selection="false"
    load-fonts="false"
    font-size="large"
    schema-style="table"
></rapi-doc>
```

the feature request is to be able to do something like this

![image](https://user-images.githubusercontent.com/182800/191680418-94f2734d-b810-4e4a-9c09-b39e82ce4f80.png)

there doesnt seem to be anything to attach it to in the markup. 

![image](https://user-images.githubusercontent.com/182800/191680631-9776803c-6784-4d1f-b905-065ed0798294.png)

(`link-get-/api/-instance` is selected here) 

suggestion: add an active class to the `div.nav-bar-path` and or

```
rapi-doc::part(section-navbar-path-item) 
rapi-doc::part(section-navbar-path-item-active) 
```

also... since i found this project... ive been singing your praise.. HOLY &@#$* what a nice set of docs and way its implemented!!! YOU ROCK!

**Comment by mrin9** [comment]
you now have few ways to achieve what you are trying to do

New attributes : `nav-accent-text-color` and `nav-active-item-marker (left-bar | colored-block)` 
New Parts: `section-navbar-item` and  `section-navbar-active-item`
Test case : https://rapidocweb.com/examples/nav-item-with-method.html#overview

to test on your own end pickup the beta from the `dist` folder

**Comment by WilliamStam** [comment]
sorry for the late reply.. this fix works REALLY well
