### ISSUE TITLE
Feature Request: Injected HTML links in nav bar

### ISSUE THREAD

**Issue by AdBotha** [rapi-doc/RapiDoc#830]
Would it be possible to have the ability to add links in the nav bar to any injected HTML? Injecting large sections of HTML sometimes causes large jumps over the injected slots (eg. `overview-top`) when navigating with the nav bar.

I have been using the `info-description-headings-in-navbar` extensively, but I am injecting HTML as we use mermaid to show flowcharts etc. It would be awesome if we are able to create links either to the slot itself (using a title parameter in the component as the Link description) or some user-defined path.

**Comment by mrin9** [comment]
I will discuss this out with our team. 
In general over usage of `slots` is something we like our users to avoid. Reason being,  the API documentation will be fragmented and spread across the `spec` and `html` file, this eventually leads to maintenance issues

**Comment by AdBotha** [comment]
Thanks. 

Makes sense to keep maintenance to as few components as possible but the `description` within the `spec` does have limitations. The ability to inject HTML in is already awesome, circumventing some of the markdown limitations, so this would just be a cherry on top.

**Comment by pmcelhaney** [comment]
I'd like to inject a checkbox next to each nav item.

![image](https://user-images.githubusercontent.com/51504/203387041-c374cd3f-7b0b-480f-b628-d2215f147b95.png)

For now I'm using JS to inject the checkboxes into the `shadowRoot`. 

```js
document
  .querySelector("rapi-doc")
  .shadowRoot.querySelectorAll(".nav-bar-path")
  .forEach((path) => {
    const input = document.createElement("input");
    input.setAttribute("type", "checkbox");
    path.prepend(input);
  });
```

I think it makes sense for unusual use cases like these. There's a risk that an internal change will break my code, but I'd rather deal with that than overcomplicated RapiDoc and make it more difficult to maintain.

**Comment by mrin9** [comment]
closing as we decided to not inject too many slots
