### ISSUE TITLE
Feature Request: x-badges support in more places

### ISSUE THREAD

**Issue by fantapop** [rapi-doc/RapiDoc#831]
Hi, I'm really liking the ability to add badges to our endpoints.  It would be great to be able to notate request and response parameters with badges as well.   This could serve to point out a new optional parameter was recently added or if some fields are experimental.

**Comment by mrin9** [comment]
I like the suggestion. 

On query and path params shouldn't be much of an issue   
but if you are asking to annotate them inside the schema view, 
then we are struggling on maintaining a balance between providing all the info and keeping it clean. 

But if you can experiment with `title` and `description` to see it can be used for badging


<img width="722" alt="image" src="https://user-images.githubusercontent.com/5056899/193954214-edf45606-6633-4451-a382-2624d0dfb391.png">

**Comment by fantapop** [comment]
I hadn't considered schema but now that you mention it, It would be ideal to have the option of displaying it there.  I see what you mean about title and description.  Those could be modified to indicate what a badge was intended for.  One drawback with that is being able to provide styling to make it stand out.  Since the templates are customizable, you could collect the data required to indicate which parameters are badged but not provide a layout example and instead leave it up to someone who wants to use it to add it into their template.

**Comment by mrin9** [comment]
not going forward with the request. It will end up being too noisy on the complex schemas, form-data, multipart request bodies etc.
However I am open for a PR, if someone can attempt one I can take it further for an approval
