### ISSUE TITLE
Feature request: Improve print support

### ISSUE THREAD

**Issue by McShelby** [rapi-doc/RapiDoc#833]
I am using RapiDoc in a [Hugo theme](https://github.com/McShelby/hugo-theme-relearn) specifically made for documentation.

The documenation is usually used by the reader in different ways:

- interactive - when reading documenation in the browser [(demo)](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/swagger/)
- static (non interactive) - when printing out documentation on paper or generating PDFs [(demo)](https://mcshelby.github.io/hugo-theme-relearn/shortcodes/swagger/index.print.html)

In the later case - even with `render-style=read` - there are still interactive elements and also parts of the generated documentation hidden which contradicts a printout. See right hand side of the [official example](https://rapidocweb.com/examples/read-mode.html#overview) where you need to click on the different response values to see the supplied explaination, either only displaying examples or schema but no both, dragging example textarea to see the whole code, etc.

I took a quick look into RapiPDF, but in my understanding, this generates a standalone PDF of the swagger definition not suitable to be embedded into further existing content.

Probably a new `render-style=print` could be a solution.

**Comment by mrin9** [comment]
thanks for the suggestion, 
RapiDoc (for rendering) and RapiPDF (for printing) is created for this reason and avoid putting too many things into one solution.

I am not sure of the below comment 
> this generates a standalone PDF of the swagger definition not suitable to be embedded into further existing content.

If a tool is trying to use this to show a printable content along with their own content, they should be able to parse this PDF too and modify or embed it into theirs too

**Comment by McShelby** [comment]
Thick fingers. Didn't meant to close the ticket.

**Comment by mrin9** [comment]
> technically the PDF can be embedded into the documentation (if you meant that be parse),

by parsing I mean an actual PDF parser which can 
- read, extract and add text and images to a `.pdf`
- add and remove pages and insert page breaks
- change margin, gutter, page page-size, page-orientation, font styles etc
- secure it using a password
- export it to other formats 

Not suggesting to convert an HTML to PDF using the browser
