### ISSUE TITLE
Add option to default to `Multiline Description`

### ISSUE THREAD

**Issue by FinHorsley** [rapi-doc/RapiDoc#838]
Sorry in advance if i'm duplicating an existing bug! 🙂 

It would be great to be able to default to `Multiline Description` in the scheme docs. Most of our API documentation doesn't fit into a single line, and it appears on first glance that there is a bug in the documentation until you see the toggle to enable multiline, as most of the documentation is truncated.

I had a look through the API docs, but couldn't see an existing setting that would achieve this

**Comment by mrin9** [comment]
use `schema-description-expanded = 'true'`



<br class="Apple-interchange-newline">
