### ISSUE TITLE
Authentication of API on RapidAPI

### ISSUE THREAD

**Issue by AnastasiaStratienko** [rapi-doc/RapiDoc#842]
Hi! Could you please share your expertise in the authorization on [RapidAPI](https://rapidapi.com/hub). 

How can I publish api endpoint without api key on [RapidAPI](https://rapidapi.com/hub).  I turned off the authorization in the setting of my API, but when clients and I invoke [our endpoint](https://rapidapi.com/DocsPortalKey/api/cryptocurrency-data2), it still asks us for token.  Is there any chance to set up API without authorization?

**Comment by mrin9** [comment]
RapidAPI and RapiDoc are two different products. You should contact RapiAPI team for your queries
