### ISSUE TITLE
Use css named variables instead of color variables 

### ISSUE THREAD

**Issue by mortada-codes** [rapi-doc/RapiDoc#845]
Thank you Team for the Effort 

i am trying to change the operation block color. i tried to override  `--nav-get-color` but it uses the color variable directly `--blue`
can we change it to the operation color variable?

![Screenshot 2022-11-18 at 1 14 53 PM](https://user-images.githubusercontent.com/20525304/202693034-425143b7-3236-4245-9db0-10d8d60fdd68.png)
![Screenshot 2022-11-18 at 1 12 29 PM](https://user-images.githubusercontent.com/20525304/202693074-a3a64ec9-cff5-4773-be04-acb02cfc16ac.png)
![Screenshot 2022-11-18 at 1 11 59 PM](https://user-images.githubusercontent.com/20525304/202693090-830c1a2b-c637-4fb9-be62-37b019ade2cd.png)

**Comment by mrin9** [comment]
it is intentional operation block color should be same as colors used to represent the HTTP methods.

It is done that way so that changing the operation color will uniformly applied to related components and makes theming more concise and easy
