### ISSUE TITLE
Does Deprecated annotation work on properties?

### ISSUE THREAD

**Issue by FinHorsley** [rapi-doc/RapiDoc#846]
Looking at https://github.com/rapi-doc/RapiDoc/issues/687, it looks like there was no visual indication of `Deprecated` on properties, but was briefly fixed in https://github.com/rapi-doc/RapiDoc/commit/39102928ca6809a0e7e881cc0ead86434c9d0b5a. However, it was then reverted in https://github.com/rapi-doc/RapiDoc/commit/3ca2c8210c3956028044b20a5479f43325f96466, does this mean that there is now no visual indication again?

**Comment by mrin9** [comment]
the reverting of Deprecated property annotation was done due to its side-effect in other sections of the UI. I do have plans to get back to it.

**Comment by rdlrt** [comment]
Just adding a +1 to say it'd be useful and leaves relying on description , which isnt as decent
