### ISSUE TITLE
show-method-in-nav-bar should default to true when use-path-in-nav-bar is on

### ISSUE THREAD

**Issue by pmcelhaney** [rapi-doc/RapiDoc#847]
When `use-path-in-nav-bar` is enabled, the request method should be visible by default.

Example from https://rapidocweb.com/examples/nav-item-as-path.html

![image](https://user-images.githubusercontent.com/51504/203379104-60d69209-c9ac-4dc4-87f8-0a7392c2f407.png)

I needed to add `show-method-in-nav-bar` to disambiguate the operations.

![image](https://user-images.githubusercontent.com/51504/203380715-2e6c2276-36d9-4757-9029-c3ce3270aa5d.png)

I'm willing to open a PR if you let me know which solution you prefer.

1. Make the default value for `show-method-in-nav-bar` equal to the value of `use-path-in-nav-bar`.
2. Don't change the API but mention in the docs that you probably want to use `use-path-in-nav-bar` if you have `show-method-in-nav-bar` enabled. Also change the example link in `use-path-in-nav-bar` to the [the example with buttons for showing the method](https://rapidocweb.com/examples/nav-item-with-method.html)
3. Something else? 

I'm leaning toward the second option because it won't be a breaking change.

**Comment by mrin9** [comment]
Thanks for the suggestion, 
I will update the docs and example to make it more clear
