### ISSUE TITLE
Feature Request: Allow changing setting the tokenUrl dynamically

### ISSUE THREAD

**Issue by jak103** [rapi-doc/RapiDoc#853]
Our server-url is https://site/api/v1, but my tokenUrl for OAuth is https://site/oauth/token. The document renders a different site based on who is logged in (different servers geographically). I can get server-url to render dynamically using the server-url attribute. However, for tokenUrl, I don't have any options to change it. It is either an absolute URL or a relative URL. If it is relative, it shows up as https://site/api/v1/oauth/token, which is not the correct URL. 

Can you add a mechanism to update the tokenUrl dynamically

**Comment by mrin9** [comment]
refer to #398 #598 #561 on how to provide multiple servers for your APIs using OpenAPI, If you are setting up oAuth then refer to https://rapidocweb.com/oauth_instructions.html
