### ISSUE TITLE
Code examples supported languages

### ISSUE THREAD

**Issue by emajo** [rapi-doc/RapiDoc#859]
Using the `x-code-samples` property to add code examples I noticed that for some languages, like php and ruby, the syntax highlighting doesn't work (even if supported by prism), it's possible to make them work somehow?

**Comment by mrin9** [comment]
This being a web component, we bundle the entire package in single bundle therefore keeping its size to minimum is one of the aspect that we consider while providing feature. 
`ruby` has a low rate of usage and `php` has certain issues import [issue](https://github.com/rapi-doc/RapiDoc/issues/680) in Prism so , they are being dropped from our highlight bundle
