### ISSUE TITLE
Full summary of an endpoint method is not shown

### ISSUE THREAD

**Issue by kmrvino** [rapi-doc/RapiDoc#864]
I am trying to create documentation page from existing web api application. Many endpoint methods have multiline summary which was generated properly in the spec doc but it's not shown on the documentation page using RapiDoc. Any suggestions ?

![image](https://user-images.githubusercontent.com/120624529/207787399-6669f537-f26c-4a3d-9e73-c9df07d1f9c9.png)

it shows only the sentence before the first full stop or new line character.

**Comment by mrin9** [comment]
check out `schema-description-expanded` in our API section to show multiple line

also there on top right corner of the schema - you should find a link to expand and collapse multi-line description
