### ISSUE TITLE
e.tags.find is not a function

### ISSUE THREAD

**Issue by m-salman-afzal** [rapi-doc/RapiDoc#872]
I'm trying to run rapiDoc with the following **html** file: 
```
<!doctype html> <!-- Important: must specify -->
<html>
<head>
  <meta charset="utf-8"> <!-- Important: rapi-doc uses utf8 characters -->
  <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
</head>
<body>
  <rapi-doc
    spec-url="https://raw.githubusercontent.com/m-salman-afzal/API_DOCS/main/test.json"
    theme = "dark"
  > </rapi-doc>
</body>
</html>
```

but I'm unable to get the docs. I'm not a front-end dev, only work on backend, so any ideas? I've done the same thing using the swagger ui, and it works fine. Is there any issue in the openApi spec that I've written?

**Comment by mrin9** [comment]
To check if the spec is correct you have various OpenAPI validators or try to validate using https://editor.swagger.io/
