### ISSUE TITLE
Release 9.3.4

### ISSUE THREAD

**Issue by jak103** [rapi-doc/RapiDoc#874]
Rapidoc is awesome! It would be great to get a release of 9.3.4. There is a lot of new code since July 2022.

I've tried to use the 9.3.4.Beta, but npm won't accept a non-semver package. 

Thanks for everything!

**Comment by mrin9** [comment]
we are finishing up with some formalities, will be releasing soon

**Comment by jak103** [comment]
Do you have an expected timeframe? Days, weeks, or months?

**Comment by mrin9** [comment]
it is now published

**Comment by jak103** [comment]
Wow! Thank you!
