### ISSUE TITLE
Filter Feature Request

### ISSUE THREAD

**Issue by maozhen520** [rapi-doc/RapiDoc#877]
hello, will rapidoc support filter some specific prefix apis in future ? i mean that when rapidoc load & resolve json/yml, some api ignore directly if those apis prefix match some feature,  for example,  /a/xxx,   /a/xxxx,  /b/xxxxx,  if i want to ignore apis start with /a,  eventually, the final html only diplays /b/xxxxx api info. thanks.

**Comment by mrin9** [comment]
you are looking for `<rapi-doc-mini>` 

This allows you to pluck only few APIs from your sepc and show them on your page. Read about it [here](https://rapidocweb.com/rapidoc-mini.html)
