### ISSUE TITLE
Failed to compile error

### ISSUE THREAD

**Issue by gmeister2** [rapi-doc/RapiDoc#878]
When I build my Vue project, I get the following error:

```
ERROR  Failed to compile with 1 error

error  in ./node_modules/rapidoc/dist/rapidoc-min.js

Module parse failed: Unexpected token (1089:224072)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

version: 9.3.4 (no error with 9.3.3) 
package manager: npm

**Comment by mrin9** [comment]
I am not sure if any of our dependencies are at fault. can you create a simple vue project with this issue and point me to that repo

**Comment by mrin9** [comment]
thanks for the response and sharing your solution/ workaround
