### ISSUE TITLE
OAuth token request includes client_id twice

### ISSUE THREAD

**Issue by wulfsberg** [rapi-doc/RapiDoc#879]
In 9.3.4, when using OAuth authentication, the user is correctly directed to the IdP login, but when RapiDoc posts a token request, the `client_id` parameter appears twice (with the same value) in the urlencoded form parameters.
While some IdP implementations may ignore this, others (correctly, AFAIK) parse it as a multivalued parameter, and rejects the request.

This was not the case in 9.3.3, where the `client_id` only appears once in the post.

**Comment by mrin9** [comment]
can you post a sample API request ?

**Comment by wulfsberg** [comment]
After returning from the login, RapiDoc posts a token request.

POST: https://idp.vejdirektoratet.dk/runtime/oauth2/token.idp

9.3.4 body:
`grant_type=authorization_code&client_id=0433a8e0-f425-4bc2-8134-fadbb96cba87&client_secret=&redirect_uri=https%3A%2F%2Ftmc.vimo.app.vd.dk%2Foauth-receiver.html&code=[long code goes here]&code_verifier=[code verifier goes here]&client_id=0433a8e0-f425-4bc2-8134-fadbb96cba87&client_secret=`

Notice the duplicated `client_id` and `client_secret`.

As opposed to 9.3.3 body:
`grant_type=authorization_code&redirect_uri=https%3A%2F%[2Ftmc.vimo.app.syndev.vd.dk](http://2ftmc.vimo.app.syndev.vd.dk/)%2Foauth-receiver.html&code=[long code goes here]&code_verifier=[code verifier goes here]&client_id=9a48ec33-f5a3-44e1-814c-8db241425b01&client_secret=`

Our IdP rejects the 9.3.4 version with the message "Missing credentials: either client_id or client_secret or both are missing."
Given how the post body looks compared to 9.3.3, it seems the `client_id` is not actually _missing_, but invalid due to the duplication.

**Comment by mrin9** [comment]
to test it use the minified file from the `dist` folder.
if you can please confirm if it worked in your case

**Comment by wulfsberg** [comment]
Looks good to me. Our IdP is happy again.

**Comment by ctron** [comment]
It looks like this hasn't been released yet.
