### ISSUE TITLE
Default scrollbar barely visible

### ISSUE THREAD

**Issue by dagnelies** [rapi-doc/RapiDoc#884]
As the image shows bellow, the scrollbar (using default styles) is barely visible. This is suboptimal for usage. I humbly suggest making it more visible in the default theme.

![image](https://user-images.githubusercontent.com/5452653/215336116-85fb56bc-f08f-4ca6-afb6-bb9f3a77d13e.png)

**Comment by mrin9** [comment]
please use [css-parts](http://localhost:8080/css-parts.html) to provide a color to the scroll bar of your choice
