### ISSUE TITLE
Problem with nullable or x-nullable fields

### ISSUE THREAD

**Issue by giorgiobazzo** [rapi-doc/RapiDoc#885]
Fields defined nullable or x-nullable in the json schema have strange characters in the content of the column "Type".

![image](https://user-images.githubusercontent.com/60367365/215596142-ecd2cb95-692d-499a-8315-62b82ecfbac5.png)

![image](https://user-images.githubusercontent.com/60367365/215595575-ced4c8f0-f15f-42f0-85c2-db7e04019910.png)

**Comment by mrin9** [comment]
seems like the OS and the browser you are using do not have some standard unicode fonts installed. Let me know whats the OS and browser that you are using and which unicode character works instead. I will see if I can get it changed/approved through our UX 

For reference the nullable fields should look like below
<img width="773" alt="image" src="https://user-images.githubusercontent.com/5056899/215676691-341016c7-702f-4de5-8dba-24eb512f5df7.png">

**Comment by giorgiobazzo** [comment]
Using windows 11 pro (PR-br) portuguese brazil.

Tested with chrome, edge, and firefox, all updated to the latest version.

Inspecting the element in the browser I have the result below:

![image](https://user-images.githubusercontent.com/60367365/215821506-d628121a-aee0-4f43-b263-148f51567c8b.png)
