### ISSUE TITLE
Is there an option to hide internal endpoints?

### ISSUE THREAD

**Issue by AlaNDGT** [rapi-doc/RapiDoc#888]
Is there currently an option to hide endpoints marked as internal using `x-internal`?

**Comment by mrin9** [comment]
no there is none at the moment

**Comment by AlaNDGT** [comment]
Planning to support it in the future?

Guess there's a [ticket](https://github.com/OAI/OpenAPI-Specification/issues/433) being discussed for an official spec but does not look like there will be anything out of it.

**Comment by HansAarneLiblik** [comment]
We've made a separate apidoc (`/apidoc` vs `/apidoc/internal`) to handle our internal endpoints. Managed to do this with custom decorators and hooks, to filter the schema.

Perhaps this can guide you to a "fix"
