### ISSUE TITLE
Request aborted on POST requests

### ISSUE THREAD

**Issue by francesco-monorchio** [rapi-doc/RapiDoc#893]
Hi everyone,

I'm using RapiDoc 9.3.4 and when I try to send POST requests to my services I receive always a "Request aborted".
With the 9.3.3 I have no problem.

**Comment by thapabishwa-plerionaut** [comment]
Could it be possible that your pre-flight requests are being rejected by your servers? I encountered a similar situation myself and had to allow it.

**Comment by mrin9** [comment]
Closing as this is not a RapiDoc Issue
