### ISSUE TITLE
The order of the "paths" groups does not respect the alphabetical order of their respective tags.

### ISSUE THREAD

**Issue by giorgiobazzo** [rapi-doc/RapiDoc#896]
The way in which the “paths” groupings are being presented does not seem to respect the alphabetical order of the “tags”. Apparently the group titles are being sorted in alphabetical order by “path”. This makes it difficult to control which group should be listed before the other.

I'll try to illustrate the problem with some prints, and I'll also leave here the json of the api description for testing.

[json sample](https://drive.google.com/file/d/1RMPE8oXd1H3_nDpakVloC8mUDTTO2b2i/view?usp=sharing)

In this example we can see in the routes:

path = /Auth/Authenticate/Token , tags[0] = "1 - Autenticação"
and
path = /AcontaAiqfome/Auth/RefreshToken/{id_empresa}, tags[0] = "5 - Aiqfome"

that the route tagged "5 – Aiqfome" is listed in the left sidebar, before "1 - Autenticação".

I believe it is because the order used is being applied to the path and not the tag.

Is this right?

![image](https://user-images.githubusercontent.com/60367365/222204241-9ef879b7-c490-4a18-b3cc-0c6ff9a4b1d8.png)

![image](https://user-images.githubusercontent.com/60367365/222204561-f41ee9c5-da37-430c-a75f-f0e638db3987.png)

![image](https://user-images.githubusercontent.com/60367365/222206131-d973a160-d3b6-487c-91c7-e1af1eb0686f.png)

**Comment by prassie** [comment]
These examples might help:
1. https://rapidocweb.com/examples/arrange-by-tags.html#overview
2. https://rapidocweb.com/examples/collapsable.html

**Comment by giorgiobazzo** [comment]
Thanks a lot for the tip, I hadn't seen that the tags were also present in the root element. I'm going to change my json document generator, to sort the tags in root.
Thanks again.

**Comment by giorgiobazzo** [comment]
Ok @prassie , I did as shown in the examples you cited and everything worked as I expected. Thank you, I will close this issue.
