### ISSUE TITLE
Wrong input for `text/plain` content type and `numeric` schema type

### ISSUE THREAD

**Issue by vpikus** [rapi-doc/RapiDoc#897]
Hi,

I'm using RapiDoc `9.3.4` and I am faced with the following issue:
RapiDoc renderers empty select input in the request body that doesn't allow to enter any value for the following content schema:

```
"content": {
  "text/plain": {
    "schema": {
      "type": "integer",
      "format": "int32"
    }
  }
}
```
<img width="1709" alt="RapiDoc UI" src="https://user-images.githubusercontent.com/4168098/222275376-a8267d70-0a13-4783-8e39-f4a2bb0cb23b.png">

But if upload the same openapi file to the swagger.io, the swagger.io rendered editable text area:
<img width="847" alt="Swagger IO" src="https://user-images.githubusercontent.com/4168098/222275739-acdfa6b6-d65d-48a8-ad89-807efa4c998b.png">

Is there any chance to fix the rendering of request body input in the same way as swagger.io does?

Full [openapi.json](https://github.com/rapi-doc/RapiDoc/files/10865679/openapi.txt)

**Comment by rps-v** [comment]
Same thing happens with `application/json` and `array` schema.

```
"requestBody": {
  "content": {
    "application/json": {
      "schema": {
        "type": "array",
        "items": {
          "type": "string"
        }
      }
    }
  }
}
```
