### ISSUE TITLE
Selected text is not hightlighted

### ISSUE THREAD

**Issue by boskokg** [rapi-doc/RapiDoc#903]
When I select some text, visually selected text is not hightlighted. 
Note:I can copy/paste the selected text. 
Note2: I am reproducing the same in the provided example [https://rapidocweb.com/examples/example1.html](https://rapidocweb.com/examples/example1.html)

I have not found that someone reported this.

**Comment by jjensenbloom** [comment]
Experiencing this as well.  Fixed by setting the --selection-bg and --selection-fg variables my css.

```
:root {
  --selection-bg: #444;
  --selection-fg: #eee;
}
```
