### ISSUE TITLE
Styling to elements inside slots

### ISSUE THREAD

**Issue by drejc** [rapi-doc/RapiDoc#906]
I have searched but could not find any solution to this except a different issue: https://github.com/rapi-doc/RapiDoc/issues/678 that had a similar problem.

If I place something like this in a slot:
```
<div slot='header'> 
        <button onclick='setApiKey()'>Get new token</button>
</div>
```

The button does not get the styles applied as other buttons - it is the default browser style.
I have tried to set styling with class="btn" and part="btn btn-outline" but it doesn't seem to work.

Any suggestion how to fix this - or is this a bug?

**Comment by mrin9** [comment]
`<slot>` is entirely a separate user area and nothing gets inherited from anywhere. But if you like to style the buttons in the same way as RapiDoc does then you can use the same css vars 
like 

```css
 background-color: var(--primary-color);
 color: var(--primary-color-invert);
 font-size: var(--font-size-small);
 border: 2px solid var(--primary-color);
```
which will take care of basic consistency and the rest of the styles you may copy as is
