### ISSUE TITLE
No requestBody textarea if schemaless file payload and no example provided

### ISSUE THREAD

**Issue by lafrech** [rapi-doc/RapiDoc#909]
I have a resource that accepts a file as request body. The `requestBody` doc looks like this:

```
        "requestBody": {
          "content": {
            "text/csv": {
              "schema": {
                "type": "string",
                "format": "binary",
                "example": "\nDatetime,1,2,3\n2020-01-01T00:00:00+00:00,0.1,1.1,2.1"
              }
            },
          }
        }
```

If the doc includes an example like in the sample above, the example is displayed and editable and can be used to TRY (in other words, the feature works just fine).

If there is no example, there is no EXAMPLE input and the TRY feature is unusable.

It is perfectly understandable that RapidDoc doesn't generate an example but I would expect an empty box to allow the used to enter content.

This doesn't happen for the typical resource where the schema defines the content of the request body and default example is generated.

**Comment by mrin9** [comment]
checkout this example https://rapidocweb.com/examples/file-upload.html#post-/upload-using-request-body

It allows the user to upload a file from local system

**Comment by mrin9** [comment]
change your content to `application/octet-stream`  and see if it solves your issue of allowing you to upload a file

**Comment by lafrech** [comment]
I'm pretty sure it will work as designed and allow users to upload a file but I don't really want that.

I'm happy with the way it works with examples right now. The example file is displayed in the doc and used a default editable payload for the TRY feature. This is great.

The only shortcoming I see is that when there is no example there is no empty box to enter stuff into.

I can live with this. In fact it is an incentive to always provide an example.

**Comment by mrin9** [comment]
okay, i will close this one 
but i will see why we decided to not provide a box if there isnt an example

**Comment by lafrech** [comment]
Yes. Displaying a box would be nice.
