### ISSUE TITLE
show-header false not obeyed when spec-url fails to load

### ISSUE THREAD

**Issue by adamsussman** [rapi-doc/RapiDoc#913]
When "show-header" is set to "false" and there is a problem loading the "spec-url" (not found, auth error, etc), then the header is still displayed.  When the spec url successfully loads, the header does not show.

```html
   <rapi-doc
       show-header = "false"
       spec-url "some failing url"
   >
```

<img width="670" alt="image" src="https://user-images.githubusercontent.com/1417810/229319396-9b11806b-3765-441a-96ad-6e0f5d4aa574.png">

**Comment by mrin9** [comment]
The reason we show the Doc title is for providing a context that which spec is having an issue. 

We have clients who uses microservices and as a result have multiple specs, which they show on a single HTML page. now it will be confusing to just show error loading spec for some of them without giving a context
