### ISSUE TITLE
Enable research on all the document

### ISSUE THREAD

**Issue by TristanLavalou** [rapi-doc/RapiDoc#915]
Hello,

I've seen search bar can be set up in normal or advanced mode, but it seems that research is focused on API routes and results. Is there an option to enable research on all the file, including text and descriptions that are before the routes ?

Thanks in advance.

**Comment by mrin9** [comment]
<img width="1061" alt="image" src="https://user-images.githubusercontent.com/5056899/231367715-4792ed2a-247e-4d61-a3b6-fd1b92ad8991.png">

by default it  searches the API paths and description (thats the text for the API routes) apart from that you may search parameters and response descriptions.

if you want to search all that u see on screen ...then use the browser's search

**Comment by TristanLavalou** [comment]
OK, thanks for your response.
