### ISSUE TITLE
[Q] Disable sticky navigation in render-style "read"

### ISSUE THREAD

**Issue by wolfgang-demeter** [rapi-doc/RapiDoc#916]
Is there an easy way or configuration to **disable the sticky navigation** when RapiDoc ist embedded in another HTML page and the parent element of RapiDoc has a `height="auto"` to avoid the scrollbars from RapiDoc-element/container and use the scrollbars of the page itself?

To reproduce:
* Goto https://rapidocweb.com/examples/example4.html (or this https://jsfiddle.net/2ug5yk6b/)
* Add attribute `render-style="read"` to `<rapi-doc>`
* Replace `height:450px` with `height:auto` in the parent `<div>` of `<rapi-doc>`
* When you scroll down, the site regularly jumps to the top, making it impossible to read the the documentation

https://user-images.githubusercontent.com/4437946/230116572-496c7864-3ba5-43cf-98a6-5e523caf4d8d.mp4

Btw. it's not an issue on mobile screens or when the navigation is not shown, e.g.:
```scss
rapi-doc::part(section-navbar) {
    display: none;
    // height: auto;
}
```

**Comment by mrin9** [comment]
you must provide a height attribute to the rapidoc either using parent or directly to rapidoc for it to work in read mode. 
as we automatically highlight the navbar based on the scroll, and in that case it must know the height. using `height:auto` defeats the purpose 
 or use `render-style=focused`
