### ISSUE TITLE
Navigation error when navigating between items in the components section

### ISSUE THREAD

**Issue by pfei5** [rapi-doc/RapiDoc#925]
First of all thank you for this incredible project. It works wonders and I am very grateful for the efforts everyone has put in.

I did stumble across an error while navigating between items inside the components section, i.e. schemas, reponses, parameters, etc..
I'm using RapiDoc 9.3.4  inside an Angular 15 project.

Navigating between items in the components section only works if I click next to the text of the item I want to navigate to.
If I click directly onto the text of the item, navigation fails.

Navigating between paths works flawlessly.

I have attached a screencast to illustrate the issue:

https://user-images.githubusercontent.com/79921672/236178223-cadd9772-78a3-4310-8f39-2e1a8dd1a186.mp4

**Comment by guillaumehottin** [comment]
I also happen to have this problem while serving rapidoc inside a simple html page that only contains the rapi-doc component inside the body.

Navigation to operations works while navigation to objects only works when clicking where there is no text.

**Comment by guillaumehottin** [comment]
After some investigation, `span` tags that are inside navbar links for operations have a `pointer-events: none` which is not the case for `span` tags inside navbar links for components as evidenced here :

https://github.com/rapi-doc/RapiDoc/blob/a6d1256f7ba0a7490f898d9924c703681d9ca3df/src/templates/navbar-template.js#L224

https://github.com/rapi-doc/RapiDoc/blob/a6d1256f7ba0a7490f898d9924c703681d9ca3df/src/templates/navbar-template.js#L260

I tried adding the `pointer-events: none` to the span in the compiled rapidoc.js and it seemed to work, but I'm not aware of any side effects it could have.

**Comment by pfei5** [comment]
Thank you 🙏🏼
