### ISSUE TITLE
advancedSearch bug

### ISSUE THREAD

**Issue by alizaga** [rapi-doc/RapiDoc#930]
The `advancedSearch` function in `common-utils.js` doesn't work as I expect.

If I want to search this description `Multiple status values can be provided with comma separated strings` of this operation [Finds Pets by status](https://rapidocweb.com/examples/example100.html#get-/pet/findByStatus) it doesn't work.

I suppose that is caused by this code of `advancedSearch` function:
```js
...
if (searchOptions.includes('search-api-descr')) {
  stringToSearch = `${stringToSearch} ${path.summary || path.description || ''}`;
}
...
```

As you can see if `path.summary` is not null the `path.description` is ignored.

Could you add a button that enables searching only in `path.description` (ignoring `path.summray`) or could you change this behaviour to take both of them in the search?

Thank you in advance.

**Comment by mrin9** [comment]
thanks for pointing out the issue
