### ISSUE TITLE
Joining the RapiDoc community on Discord

### ISSUE THREAD

**Issue by tim-neill-provtech** [rapi-doc/RapiDoc#932]
Unfortunately your join link is now dead. I would love to see access the community if it still exists.

Huge thanks for this wonderful product! 

![Screenshot from 2023-06-05 11-17-05](https://github.com/rapi-doc/RapiDoc/assets/118756884/24ebc160-fc29-42de-8771-bc98782b3850)

**Comment by AdrianMachado** [comment]
@tim-neill-provtech https://discord.gg/HVr5Wn78HF
