### ISSUE TITLE
Long summaries are truncated after first dot symbol.

### ISSUE THREAD

**Issue by sokod** [rapi-doc/RapiDoc#933]
It is possible to display a long summary in full without truncating it?

**Comment by mrin9** [comment]
In RapiDoc, Summaries are used in tight spaces such as Nav Items and for operation headings in view mode.
Therefore RapiDoc expects them to be one liner which make sense. therefore it truncates them after the first sentence (_after dot_) 

If you have long summaries consider using the `description` or if you have a use case where if must show the entire summary even though it may look little off space then do not use dots in the summary. But the current behavior is something our clients thinks is a good trade off between flexibility and simplicity
