### ISSUE TITLE
OpenGIS Web API's

### ISSUE THREAD

**Issue by Adriaanse** [rapi-doc/RapiDoc#940]
The OpenGIS consortium, also known as OGC has developed several Web API standards related to Geospatial information services, like the [WMS (Web Map Service)](https://www.ogc.org/standard/wms/), [WFS (Web Feature Service)](https://www.ogc.org/standard/wfs/)  and several others.

When trying to use Rapidoc to create test pages for such services we run into problems because these services typically use a "path" which includes at least one hardcoded parameter, "request" and the type of this request determines the rest of the parameters so for example the WMS protocol has these paths:

path?request=getcapabilities&service
path?request=getmap
path?request=getFeatureinfo

Each has a separate set of parameters that follow so trying to treat them all as a single endpoint or path will result in total confusion.

The problem now is that rapidoc insists on adding a second question mark between this path and the first parameter that follows without first checking if one is already there and an ampersand should be used.

Swagger UI will do this without problems but we would really prefer to use RapiDoc ?

**Comment by mrin9** [comment]
@Adriaanse , let me look at it if we can take care of this situation

**Comment by mrin9** [comment]
this works in `v9.3.6`
