### ISSUE TITLE
Process extension values defined for properties of referenced objects

### ISSUE THREAD

**Issue by charithe** [rapi-doc/RapiDoc#944]
Consider a parameter definition like the following:

```json
        "parameters": [
          {
            "name": "body",
            "description": "Description",
            "in": "body",
            "required": true,
            "schema": {
              "$ref": "#/definitions/Foo"
            }
          }
        ]
```

The `Foo` object is defined as:

```json
    "Foo": {
      "type": "object",
      "properties": {
        "bar_field": {
          "type": "string",
          "example": "bar_value",
          "x-example-show-value": false,
          "x-fill-example": false
        },
        "baz_field": {
          "type": "string",
          "example": "baz_value",
          "x-example-show-value": false,
          "x-fill-example": false
        }
      }
    }
```

It seems that the `x-fill-example` and `x-example-show-value` extension values are not processed by Rapidoc when generating the example. It'd be nice to be able to exclude certain properties from nested objects from appearing in the generated example.

**Comment by mrin9** [comment]
`x-fill-example` and `x-example-show-value` are defined at request level
If you like to include/exclude values from the schema then OpenAPI already provides an way to do that 
Ise `One-Of` and `Any-Of` combinations to define your schema and RapiDoc will generate various possible combinations of the example values checkout this [test-case ](https://rapidocweb.com/examples/oneof.html)
