### ISSUE TITLE
RapiDoc does not use url with server variables

### ISSUE THREAD

**Issue by sag-camos** [rapi-doc/RapiDoc#946]
We defined an url in the servers-section of our API-json file with two variables:
![grafik](https://github.com/rapi-doc/RapiDoc/assets/56827552/500b3220-1683-4ab8-b168-ec9c7324caea)

In RapiDoc it is possible to edit the variables and it is displayed correcty in APIServer-Section:
![grafik](https://github.com/rapi-doc/RapiDoc/assets/56827552/461ae0e4-4bb1-49ac-a6f7-e2db10824c2e)

But at any endpoint the url ist displayed wrong:
![grafik](https://github.com/rapi-doc/RapiDoc/assets/56827552/12fcb8f0-fbff-47e2-933d-b6a7c1c597e9)

The combo box shows two times the same wrong url. In rapidoc api-example there is no combo box, but we could not find an option to disable it.

Does anyone have suggestions how to fix this problem?

**Comment by mrin9** [comment]
this issue is obsolete now . The end-point list of servers have been removed as it cannot handle server url templates constructed using variables
