### ISSUE TITLE
Create a new release

### ISSUE THREAD

**Issue by cjmaio** [rapi-doc/RapiDoc#957]
Hello all!

I need a fix that was done earlier this year, but doesn't look to have been released. Any chance of doing a patch release so the fix https://github.com/rapi-doc/RapiDoc/pull/883 is included?

**Comment by v-radev** [comment]
I also need 9.3.5 to be released to take advantage of a bug fix please.

**Comment by gr33nwhal3** [comment]
Hello, thank you for this amazing tool.

I also need the new `fetched-try` event. Do you have any idea about the next release ?

**Comment by mrin9** [comment]
new release created
