### ISSUE TITLE
RapiDoc not reading springfox json correctly

### ISSUE THREAD

**Issue by RathoreGovind** [rapi-doc/RapiDoc#959]
I have implemented swagger using springfox in a sample spring mvc application.  I want to use rapiDoc to generate API documentation from the generated API specification JSON
I have specified request header in my API using the @ApiImplicitParam it is reflecting on JSON as well as on swagger-ui.html but when I use the same JSON in rapiDoc It is not showing the Request headers 

I'm using swagger2 and springfox version 2.5.0. The Rapidoc looks like

 [this](https://github.com/rapi-doc/RapiDoc/assets/121210976/799e5caf-76d0-4cd8-ae2c-4fb6d71c66ef) 

 and swagger-ui looks like 

[this](https://github.com/rapi-doc/RapiDoc/assets/121210976/4beb628c-378d-49d1-9b3f-c2eb0170ede5) 

and the code snipett is 

[this](https://github.com/rapi-doc/RapiDoc/assets/121210976/4876453f-4723-4628-ab39-8eca0b36a65b)

The rendered JSON found at v2/api-docs
`{
    "swagger": "2.0",
    "info": {
        "description": "Rest API Example",
        "version": "1",
        "title": "Rest API",
        "contact": {
            "name": "Edwin",
            "url": "http://edwin.baculsoft.con",
            "email": "edwin@baculsoft.com"
        },
        "license": {
            "name": "Apache License"
        }
    },
    "host": "localhost:8080",
    "basePath": "/spring-mvc-helloworld-example",
    "tags": [
        {
            "name": "hello-world-controller",
            "description": "Hello World Controller"
        }
    ],
    "paths": {
        "/hello": {
            "get": {
                "tags": [
                    "hello-world-controller"
                ],
                "summary": "Testing Page",
                "operationId": "sayHelloUsingGET",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "*/*"
                ],
                "parameters": [
                    {
                        "in": "body",
                        "name": "model",
                        "description": "model",
                        "required": false,
                        "schema": {
                            "$ref": "#/definitions/Model"
                        }
                    },
                    {
                        "name": "header1",
                        "in": "header",
                        "description": "header1",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "header2",
                        "in": "header",
                        "description": "header2",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "name": "header3",
                        "in": "header",
                        "description": "header3",
                        "required": true,
                        "type": "string"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized User"
                    },
                    "403": {
                        "description": "Forbidden User"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                }
            }
        }
    }
}`

Please can you advice how I can fix this issue 

Thanks,
Govind.

**Comment by prassie** [comment]
rendered JSON is missing model schema referred in `"schema": { "$ref": "#/definitions/Model" }`

**Comment by RathoreGovind** [comment]
It works when the "schema": { "$ref": "#/definitions/Model" }  is provided thanks for that.

When I provide it the following  [JSON](https://github.com/rapi-doc/RapiDoc/files/12548499/ShowParamJson.txt) it works.
`{
    "basePath": "/spring-mvc-helloworld-example",
    "definitions": {
        "Model": {
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "host": "localhost:8080",
    "info": {
        "contact": {
            "email": "edwin@baculsoft.com",
            "name": "Edwin",
            "url": "http://edwin.baculsoft.con"
        },
        "description": "Rest API Example",
        "license": {
            "name": "Apache License"
        },
        "title": "Rest API",
        "version": "1"
    },
    "paths": {
        "/hello": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "operationId": "sayHelloUsingGET",
                "parameters": [
                    {
                        "description": "model",
                        "in": "body",
                        "name": "model",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model"
                        }
                    },
                    {
                        "description": "header1",
                        "in": "header",
                        "name": "header1",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "header2",
                        "in": "header",
                        "name": "header2",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "header3",
                        "in": "header",
                        "name": "header3",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized User"
                    },
                    "403": {
                        "description": "Forbidden User"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "summary": "Testing Page",
                "tags": [
                    "hello-world-controller"
                ]
            }
        },
        "/bye": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "operationId": "bye",
                "parameters": [
                    {
                        "default": "token",
                        "in": "header",
                        "name": "token",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "default": "num",
                        "in": "header",
                        "name": "num",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "default": "xyz",
                        "in": "header",
                        "name": "xyz",
                        "required": false,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
               "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized User"
                    },
                    "403": {
                        "description": "Forbidden User"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "summary": "bye",
                "tags": [
                    "hello-world-controller"
                ]
            }
        }
    },
    "swagger": "2.0",
    "tags": [
        {
            "description": "Hello World Controller",
            "name": "hello-world-controller"
        }
    ]
}`

 Take a look at the UI screen shot 

[Part1](https://github.com/rapi-doc/RapiDoc/assets/121210976/d3a40d4f-f066-4780-9bcc-1b81c0740397),[Part2](https://github.com/rapi-doc/RapiDoc/assets/121210976/6ad57150-0c2f-4ca2-8df0-6d50473a50a4)
Here you can see it show all the parameters and header for the request.


But with this [JSON](https://github.com/rapi-doc/RapiDoc/files/12548557/DontShow.txt) with  missing schema 
`{
    "basePath": "/spring-mvc-helloworld-example",
    "definitions": {
        "Model": {
            "properties": {
                "name": {
                    "type": "string"
                }
            },
            "type": "object"
        }
    },
    "host": "localhost:8080",
    "info": {
        "contact": {
            "email": "edwin@baculsoft.com",
            "name": "Edwin",
            "url": "http://edwin.baculsoft.con"
        },
        "description": "Rest API Example",
        "license": {
            "name": "Apache License"
        },
        "title": "Rest API",
        "version": "1"
    },
    "paths": {
        "/hello": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "operationId": "sayHelloUsingGET",
                "parameters": [
                    {
                        "description": "model",
                        "in": "body",
                        "name": "model",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model"
                        }
                    },
                    {
                        "description": "header1",
                        "in": "header",
                        "name": "header1",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "header2",
                        "in": "header",
                        "name": "header2",
                        "required": true,
                        "type": "string"
                    },
                    {
                        "description": "header3",
                        "in": "header",
                        "name": "header3",
                        "required": true,
                        "type": "string"
                    }
                ],
                "produces": [
                    "*/*"
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized User"
                    },
                    "403": {
                        "description": "Forbidden User"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "summary": "Testing Page",
                "tags": [
                    "hello-world-controller"
                ]
            }
        },
        "/bye": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "operationId": "bye",
                "parameters": [
				{	
					 "description": "model",
                        "in": "body",
                        "name": "model",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/Model1"
                        }
				},
                    {
                        "default": "token",
                        "in": "header",
                        "name": "token",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "default": "num",
                        "in": "header",
                        "name": "num",
                        "required": false,
                        "type": "string"
                    },
                    {
                        "default": "xyz",
                        "in": "header",
                        "name": "xyz",
                        "required": false,
                        "type": "string"
                    }
                ],
                "produces": [
                    "application/json"
                ],
               "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "401": {
                        "description": "Unauthorized User"
                    },
                    "403": {
                        "description": "Forbidden User"
                    },
                    "404": {
                        "description": "Not Found"
                    }
                },
                "summary": "bye",
                "tags": [
                    "hello-world-controller"
                ]
            }
        }
    },
    "swagger": "2.0",
    "tags": [
        {
            "description": "Hello World Controller",
            "name": "hello-world-controller"
        }
    ]
}`
 it will outright ignore all of the parameters, take look at these examples
[Part1](https://github.com/rapi-doc/RapiDoc/assets/121210976/1911d52f-4e77-4ddf-87d1-da18ec393ebd),[Part2](https://github.com/rapi-doc/RapiDoc/assets/121210976/61ce01eb-75a1-432a-b084-052d80c2f7e8)

If I try to open the same [JSON](https://github.com/rapi-doc/RapiDoc/files/12548557/DontShow.txt) on Swagger.io it will show the available parameters take a look at these 
[Part1](https://github.com/rapi-doc/RapiDoc/assets/121210976/d84212ef-74db-4f9d-81f7-1d0736c06e21),[Part2](https://github.com/rapi-doc/RapiDoc/assets/121210976/5dfb624a-f3de-4981-98f7-8d2502a46fb9)

Is necessary for the JSON not to miss any thing or is there a way I can make it work.

Thanks,
Govind

**Comment by prassie** [comment]
1. Please embed the images instead of separate links for easier reading as shown below
2. Please include formatted json for easier reference
3. Seems the definitions are stored in a separate file in the basePath, which is accessible/loaded/used by Swagger, but RapiDoc might need more info. In RapiDoc need to include the other file path in ref, if the referenced detail is not part of the same file like `$ref: 'templates.json#/paths/~1templates'`; `templates.json` is a different file from `main.json` which has this reference. You need to include the 
4. Check this example for remote reference: https://rapidocweb.com/examples/external-refs.html#servers
  - Spec file: https://rapidocweb.com/specs/external-refs.yaml 

![image](https://github.com/rapi-doc/RapiDoc/assets/1357831/aca8f7a4-b557-4264-aa2b-876e70fe5bb3)

**Comment by RathoreGovind** [comment]
I will use embedded images thanks for the feedback.
It seems I was unable to explain myself. 
I only have one JSON file, but it is missing some references.

Due to my application constraints it is only possible to use the springfox swagger 2 implementation.

Due to my application constraints it is producing JSON with missing references in some API's which I'm unable to fix and rapiDoc is not showing parameters of any API even if the references to those parameters are present in my JSON.

On the other hand if I open the same JSON on [swagger.io](https://editor.swagger.io/?_ga=2.64183530.477781642.1694427926-2029191764.1694427924) it is able to show me the API parameter and also show me the error in my JSON file 

![image](https://github.com/rapi-doc/RapiDoc/assets/121210976/6ff37942-8502-4eb4-80f0-e26bb6fef4e8)
and
![image](https://github.com/rapi-doc/RapiDoc/assets/121210976/9ccbee99-effb-4215-a324-43124426dfd7)


but rapiDoc is not showing the same 
![image](https://github.com/rapi-doc/RapiDoc/assets/121210976/30ff2ce3-3405-490e-bc66-3f39c75036e7)



So is there a way by which rapiDoc can show the parameters present in my [JSON ](https://github.com/rapi-doc/RapiDoc/files/12575266/DontShow.txt)

Thanks.
