### ISSUE TITLE
Nested operation tags 

### ISSUE THREAD

**Issue by dsparkplug** [rapi-doc/RapiDoc#962]
Hi,

Is it currently possible to display nested tags in the left-hand navigation.

e.g. If the operation Tags are defined as "Mammal|Elephant",  "Mammal|Monkey" and  "Bird|Parrot"

```
Mammal                                  V

  Elephant                              V
  GET Get a elephant by id
  PUT Add a new elephant

  Monkey                                V
  GET Get a monkey by id
  PUT Add a new monkey

Bird                                    V

 Parrot                                 V
  GET Get a parrot by id
  PUT Add a new parrot

```

If not, is this planned in the future?

**Comment by WilliamStam** [comment]
right now if you have routes with multiple tags then it ends up "duplicating" the route into each tag accordion. slightly irritating with a largeish api. resorted to finding all tags and turning them into a pipe separated string

```
tags = ["instances","accounts","meters"]
```
becomes
```
tags = ["instances | accounts|meters"]
```

![image](https://github.com/rapi-doc/RapiDoc/assets/182800/e8d91b08-b0fc-468a-9add-a6f9434651de)


(trying to figure out how to have all the tag groups closed now tho.. i cant get the `x-tag-expanded` thing to work :(

**Comment by wparad** [comment]
What is a nested Tag? Is that in the spec?

**Comment by WilliamStam** [comment]
> What is a nested Tag? Is that in the spec?

https://github.com/swagger-api/swagger-ui/issues/5969

not in the spec. but it does fall part of the display side which is what rapidoc does.

**Comment by mrin9** [comment]
routes with multiple tags allow you to model your API docs as independent feature
for instance all the APIs needed for `Accounts` will be under it and all the APIs needed `Budget` will be under it and they can have repeating APIs. 
You can also decide to show only APIs from a particular tag in your site 

Thats what [RapiDoc-Mini ](https://rapidocweb.com/rapidoc-mini.html) does.

Tags cannot be treated to extract any hierarchy information from it. therefore closing this request
