### ISSUE TITLE
Can't debug OpenApiParser.resolve

### ISSUE THREAD

**Issue by erguotou520** [rapi-doc/RapiDoc#965]
Thanks for this great API explorer tool. We are building an API builder tool and use RAPI to show the API spec. Now we are stuck at RAPI page when the query contains a deep nested and circular param.

So I decide to debug RAPI source code. The code now stuck at file `spec-parser.js` and line 13

```js
specMeta = await OpenApiParser.resolve({ url: specUrl, allowMetaPatches: false });
```

But the `@apitools/openapi-parser` library's Github url is 404 now, I can't debug the source code. I found the repo is published by @mrin9 , please help.

**Comment by wparad** [comment]
I think this is related to https://github.com/rapi-doc/RapiDoc/issues/720

**Comment by mrin9** [comment]
I am sorry `@apitools/openapi-parser` is a closed source and there are contributions from other committers who would not like to open it up. You may use your choice of OpenAPI resolver and resolve your spec and then submit an OpenAPI compliant spec to RapiDoc
