### ISSUE TITLE
Visual issues in mobile: authentication info and tooltips are on top of Header

### ISSUE THREAD

**Issue by rdwebdesign** [rapi-doc/RapiDoc#967]
The authentication info ![image](https://github.com/rapi-doc/RapiDoc/assets/1385443/3435f033-a31e-44a7-9d52-2b467ef0e0e7) is rendered on top of the header, in mobile devices, when `render-style="view"`.

This can be replicated using the rapidoc example:
- access this page: https://rapidocweb.com/examples/example100.html _(using a mobile device)_;
- change render style to `view`;
- scroll down and open the `POST /pet/{petID}/uploadImage` endpoint;
- some elements will be rendered on top of the header.
![image](https://github.com/rapi-doc/RapiDoc/assets/1385443/0652e9cd-9d0f-4959-a6f9-a1f7911b1afc)

**Suggested fix:**
Adding `position: relative` to `endpoint-body` element will fix the position.

![rapidoc-mobile-endpoint-body-error](https://github.com/rapi-doc/RapiDoc/assets/1385443/417cf2e4-8d9e-4875-bab1-8d696c8607b7)
**Note:** `position: relative` is already used in larger screens, but not in the small ones.

**Comment by mrin9** [comment]
this is fixed in `v9.3.7` in smaller screens authentication info  is hidden
