### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by kimsagro1** [rapi-doc/RapiDoc#968]
Given that the last release was January, I was wondering if this project is still being maintained

**Comment by stanislaw** [comment]
It would be great to know the status even if it is not a positive answer. We are starting to depend on this library in https://github.com/strictdoc-project/strictdoc.

cc @villanella

**Comment by wparad** [comment]
@stanislaw If you need immediate confirmation, we maintain a successful  and actively maintained fork over at https://github.com/authress-engineering/openapi-explorer

**Comment by pavlovmike** [comment]
@mrin9 Hi! It may be a good idea to archive this project - in case you have no time and the possibility to maintain it. A lot of community members still try to make pull requests and wait for release )

**Comment by kimsagro1** [comment]
@wparad Is [openapi-explorer](https://github.com/authress-engineering/openapi-explorer) a drop-in replacement?

**Comment by wparad** [comment]
> @wparad Is [openapi-explorer](https://github.com/authress-engineering/openapi-explorer) a drop-in replacement?

There are quite a number of improvements over this project, too many to list here. So I wouldn't say it is a drop in replacement, but for the most part it is a superset of what is here. That means you should be able to transition without much work. If you find issues doing the conversion, we can create a page on how to migrate from this project to the OpenAPI Explorer. You can open a ticket to track issues over there, and we can use that fuel a `migration guide`.

**Comment by mrin9** [comment]
the project is still maintained however the commits have slowed down as it has achieved a level of stability. we have recently upgraded all the core packages, merged several contributions and improved on performance
