### ISSUE TITLE
The big enum is not fully displayed in the body schema

### ISSUE THREAD

**Issue by PetrChalov** [rapi-doc/RapiDoc#973]
Enum that does not fit into the display area is not displayed completely.
![image](https://github.com/rapi-doc/RapiDoc/assets/13746723/6eac5df1-bb09-4834-8e52-239c2922bfd9)

**Comment by mrin9** [comment]
enum values or for that matter any other text like descriptions will get truncated if you use single line descriptions . You can 
  - either click on the `Multiline description` top-right corner of schema box to show all the values 
  - or use [`schema-description-expanded="true"`](https://rapidocweb.com/api.html#att-schema) option

single line view
<img width="892" alt="image" src="https://github.com/user-attachments/assets/1e081532-8310-46cd-b429-5b198fa64e07">

 here is multiline view

<img width="892" alt="image" src="https://github.com/user-attachments/assets/28f1e8d9-9735-4b5c-9f34-cfe36747fd55">
