### ISSUE TITLE
Question: get the token used for auth to add that to the spec-url 

### ISSUE THREAD

**Issue by WilliamStam** [rapi-doc/RapiDoc#978]
Im trying to have the docs show only the endpoints that the user has access to. this works in the backend when viewing `/openapi.json?token=xxxx`. is there a way with a before-load to append the query string or whatever the "try now" auth block adds but to the spec-url

**Comment by mrin9** [comment]
if your backend is returning a `JSON` you can programmatically load the spec using `loadSpeac()` method. Refer to this [example](https://github.com/rapi-doc/RapiDoc/blob/master/docs/examples/example9.html)
