### ISSUE TITLE
No indication of which properties are required within a request body schema

### ISSUE THREAD

**Issue by marshmn** [rapi-doc/RapiDoc#986]
When displaying a request body schema, there is no indication of which properties are required and which are optional. Thee is no indication, regardless of whether table or object view is used.

![Screenshot from 2023-12-27 12-51-21](https://github.com/rapi-doc/RapiDoc/assets/4307033/2d685674-5d4f-4771-a0b2-d2ff3c0f6b07)

In the above example, the `email_address` property is marked with `required: false` in the OpenAPI spec, whereas the other two properties are marked as `required: true`, but there is nothing to indicate this in RapiDoc.

**Comment by mrin9** [comment]
can you provide me with a sample spec to reproduce the issue ?
