### ISSUE TITLE
Content type should be indicated in consistent place for request body and response

### ISSUE THREAD

**Issue by marshmn** [rapi-doc/RapiDoc#989]
The content type (e.g. `application/json`) is shown in different places for the request body and response. For request body it is shown next to the title, whereas for the response it is shown top-right of the table.

I think it would be better to always place it to the top-right of the table so that's consistent for both.

I was caught out by this at least once, looking for the content type above the request body table and missing the fact it was somewhere different instead.

![Screenshot from 2023-12-27 13-05-56](https://github.com/rapi-doc/RapiDoc/assets/4307033/f4e696b6-c617-4b6e-b991-d39e11498437)

**Comment by mrin9** [comment]
the reason it is done like that because request-body can be of many media-types and not all media-types will have a schema table 

for example checkout this example where you can change request-body  media type from `application/json` to another

**Comment by marshmn** [comment]
> the reason it is done like that because request-body can be of many media-types and not all media-types will have a schema table
> 
> for example checkout this example where you can change request-body media type from `application/json` to another https://rapidocweb.com/examples/request-body-multiple.html#post-/item-price

I take your point - and you're right that there are definitely some complications to consider. 

Looking at the example you've linked to though, isn't the same problem also true for the response? The response has two content-type options, and if `text/html` is selected, the schema tab looks broken - presumably for the same reason you've indicated.

It still feels like something could be done to be more consistent in where the content-type indication and/or selector is placed for both request and response?
