### ISSUE TITLE
Clicking Auth end-point button fail to scroll to Auth section

### ISSUE THREAD

**Issue by CoenraadS** [rapi-doc/RapiDoc#994]
![Recording 2024-01-01 at 11 10 00](https://github.com/rapi-doc/RapiDoc/assets/5593825/a5c11edc-05d5-4e73-8059-4b2c9c3bf869)

v9.3.4

```
    <rapi-doc 
    spec-url="/swagger/v1/swagger.json" 
    theme="light"
    primary-color = "#025B82"
    show-header="false" 
    render-style="read" 
    use-path-in-nav-bar="true" 
    nav-item-spacing="compact" 
    show-method-in-nav-bar="as-colored-text"
    persist-auth="true"
    >
    </rapi-doc>
```

Example swagger:

[swagger.json](https://github.com/rapi-doc/RapiDoc/files/13802516/swagger.json)
 
 It also happens on the online example, try clicking the auth button on this endpoint:
 
 https://rapidocweb.com/examples/read-mode.html#get-/store/inventory

**Comment by mrin9** [comment]
this seems to be working in `v9.3.6` 
![Screen-Recording-2024-09-19-at-10 43 56 AM (1)](https://github.com/user-attachments/assets/8364e23f-4df1-42c6-858e-8b59149f24b1)
